import type React from 'react';
import type { Components } from 'react-markdown';
import type { AssistantNavStatus } from '@/app/assistantNavStatus';
import type { ChatMessage, ChatRuntimeSelection, ChatSession, KubernetesCluster } from '@/types';
import type { LiveRunTrace } from '@/features/kubernetes-cluster-detail/types';

export interface TargetChatViewProps {
  target: KubernetesCluster;
  isDark: boolean;
  titleKey?: string;
  descriptionKey?: string;
  promptTitleKey?: string;
  promptBodyKey?: string;
  suggestionKeys?: string[];
  inputPlaceholderKey?: string;
  noChatAccessKey?: string;
  footerKey?: string;
  footerNoAccessKey?: string;
  canChat: boolean;
  isConversationOwner: boolean;
  conversationNotice: string | null;
  recentActivityWarning: ChatSession['recentActivityWarning'] | null;
  canRequestWriteRuns: boolean;
  canApproveWriteActions: boolean;
  canCancelRuns: boolean;
  canDeleteSessions: boolean;
  isRunActive: boolean;
  isSessionsLoading: boolean;
  isLoadingEarlierMessages: boolean;
  hasEarlierMessages: boolean;
  activeRunId: string | null;
  isCancellingRun: boolean;
  inputValue: string;
  sessions: ChatSession[];
  activeSessionId: string | null;
  assistantMarkdownComponents: Components;
  userMarkdownComponents: Components;
  visibleMessages: ChatMessage[];
  runTracesByRunId: Record<string, LiveRunTrace>;
  sessionAssistantStatuses?: Record<string, AssistantNavStatus>;
  transcriptRef: (node: HTMLDivElement | null) => void;
  onChatScroll: () => void;
  onLoadEarlierMessages: () => void | Promise<void>;
  onInputChange: (value: string) => void;
  onSend: (overrideInput?: string, runtimeSelection?: ChatRuntimeSelection) => void | Promise<void>;
  onEditLastUserMessage: (messageId: string, nextContent: string, runtimeSelection?: ChatRuntimeSelection) => void | Promise<void>;
  onApprove: (approvalId: string) => void | Promise<void>;
  onReject: (approvalId: string) => void | Promise<void>;
  onSelectSession: (sessionId: string) => void;
  onCreateSession: () => void;
  onDismissRecentActivityWarning: () => void;
  onOpenRecentActivitySession: (sessionId: string) => void;
  onDeleteSession: (sessionId: string) => Promise<void>;
  onCancelRun: () => Promise<void>;
  isInFlightAssistantPlaceholder: (message: ChatMessage) => boolean;
  displayMode?: 'full' | 'panel';
  onClose?: () => void;
  onMaximize?: () => void;
}
