import { describe, expect, it } from 'vitest';
import {
  approvalCheckpoint,
  appClusterChatRuntime,
  assistantTurn,
  chatGateDialog,
  chatTranscriptStates,
  conversationAssistantStatuses,
  chatSessionSync,
  chatSubmit,
  chatView,
  conversationHistory,
  enLocale,
  markdownComponents,
  messageActions,
  styles,
  targetChatRunWatcher,
  traceFooter,
  useTargetChat,
  userMessageTurn,
  zhLocale
} from '@/stylesTestSupport';

describe('target chat polish contracts', () => {
  it('keeps desktop conversation history as a non-blocking route rail', () => {
    expect(chatView).toContain('setIsHistoryOpen(true)');
    expect(chatView).toContain('setIsHistoryOpen(false)');
    expect(chatView).toContain('desktopHistoryPanelId');
    expect(chatView).toContain('relative hidden h-full shrink-0 overflow-visible border-r border-ui-border bg-ui-surface shadow-sm lg:flex');
    expect(chatView).toContain('absolute inset-0 z-[110] lg:hidden');
    expect(chatView).toContain('usesOverlayHistory');
    expect(chatView).toContain('historyPanelRef.current?.focus');
    expect(chatView).toContain('getFocusableHistoryElements');
    expect(chatView).toContain('getHistoryFocusWrapIndex');
    expect(chatView).toContain('aria-modal="true"');
    expect(chatView).toContain('aria-hidden="true"');
    expect(chatView).toContain('aria-pressed={isHistoryOpen}');
    expect(chatView).toContain('absolute left-0 top-1/2 z-20');
    expect(chatView).toContain('right-[-2.25rem] top-1/2');
    expect(chatView).toContain('side="right"');
    expect(chatView).toContain("t('chat.hideHistory')");
    expect(chatView).toContain("t('chat.showHistory')");
    expect(chatView).toContain('<History className="h-4 w-4" />');
    expect(chatView).not.toContain('[clip-path:polygon');
    expect(chatView).toContain('lg:grid-cols-[minmax(0,1fr)_auto]');
    expect(chatView).not.toContain("Tooltip content={t('chat.newChat')}");
    expect(chatView).toContain('const handleCreateSessionClick = () => {');
    expect(chatView).toContain('onCreateSession();');
    expect(chatView).toContain('requestComposerFocus();');
    expect(chatView).toContain('onClick={handleCreateSessionClick}');
    expect(chatView).not.toContain('lg:grid-cols-[auto_minmax(0,1fr)_auto]');
    expect(conversationHistory).toContain('aria-current={isActive ?');
    expect(conversationHistory).toContain("t('chat.conversationHistory')");
    expect(conversationHistory).toContain("t('chat.historyContext', { name: appName })");
    expect(conversationHistory).not.toContain('onCreateSession');
    expect(conversationHistory).not.toContain('onClose');
    expect(chatView).toMatch(/const selectSession = \(sessionId: string\) => \{\s+if \(sessionId !== activeSessionId\) clearComposerAttachments\(\);\s+onSelectSession\(sessionId\);\s+\};/);
    expect(chatView).not.toContain("event.key === 'Escape'");
    expect(chatView).not.toContain('xl:w-80');
  });

  it('renders approvals as inline operational checkpoints', () => {
    expect(approvalCheckpoint).toContain('interface ApprovalCheckpointProps');
    expect(approvalCheckpoint).toContain('data-chat-approval-checkpoint="true"');
    expect(approvalCheckpoint).toContain('const StatusIcon');
    expect(approvalCheckpoint).toContain('const statusToneClass');
    expect(approvalCheckpoint).toContain("t(`chat.approvalStatusLabel.${approvalStatus}`)");
    expect(approvalCheckpoint).toContain('const approvalSummary = cleanText(approval.summary) || fallbackApprovalSummary(approval, t);');
    expect(approvalCheckpoint).toContain("String(value ?? '')");
    expect(approvalCheckpoint).toContain("approval.toolName === 'apply_remediation'");
    expect(approvalCheckpoint).toContain("t('chat.approvalFallbackSummary.applyRemediation'");
    expect(approvalCheckpoint).toContain("t('chat.approvalFallbackTarget.selectedTarget')");
    expect(approvalCheckpoint).toContain("t('chat.approvalFallbackSummary.genericTarget'");
    expect(approvalCheckpoint).toContain('className="px-4 py-4"');
    expect(approvalCheckpoint).toContain('<h3 className="text-sm font-semibold leading-6 text-ui-text">{t(\'chat.guardTitle\')}</h3>');
    expect(approvalCheckpoint).toContain('<p className="mt-1 break-words text-base font-semibold leading-6 text-ui-text">');
    expect(approvalCheckpoint).toContain("t('chat.approvalAdvancedDetails')");
    expect(approvalCheckpoint).toContain('<details');
    expect(approvalCheckpoint).toContain('type-code mt-1 max-h-36');
    expect(chatSessionSync).toContain('summary: approval.summary');
    expect(targetChatRunWatcher).toContain(
      "const summary = typeof event.payload?.summary === 'string' ? event.payload.summary : undefined;"
    );
    expect(assistantTurn).toMatch(/<ApprovalCheckpoint[\s\S]*?onApprove=\{onApprove\}/);
    expect(enLocale).toContain("approvalCheckpoint: 'Approval checkpoint'");
    expect(enLocale).toContain("approvalAdvancedDetails: 'Advanced details'");
    expect(enLocale).toContain("guardTitle: 'Approve the following action?'");
    expect(enLocale).toContain("approvalStatusLabel: {");
    expect(enLocale).toContain("approvalFallbackSummary: {");
    expect(enLocale).toContain("genericTarget: 'Run {{tool}} against {{target}}.'");
    expect(enLocale).toContain("approveAction: 'Approve once'");
    expect(zhLocale).toContain("approvalCheckpoint: '批准检查点'");
    expect(zhLocale).toContain("approvalAdvancedDetails: '高级详情'");
    expect(zhLocale).toContain("guardTitle: '批准以下操作？'");
    expect(zhLocale).toContain('approvalStatusLabel: {');
    expect(zhLocale).toContain('approvalFallbackSummary: {');
    expect(zhLocale).toContain("genericTarget: '对 {{target}} 运行 {{tool}}。'");
    expect(zhLocale).toContain("approveAction: '批准一次'");
  });

  it('keeps polish shared across transcript, composer, and trace surfaces', () => {
    expect(assistantTurn).toContain('data-chat-assistant-turn="true"');
    expect(assistantTurn).toContain('className="group w-full min-w-0 text-sm font-medium text-ui-text"');
    expect(assistantTurn).toContain("import { MessageActions }");
    expect(assistantTurn).toContain("aria-label={t('chat.roleAssistant')}");
    expect(assistantTurn).toContain('<span className="sr-only">{t(\'chat.roleAssistant\')}</span>');
    expect(assistantTurn).not.toContain('mb-2 flex max-w-[72ch] items-center justify-between');
    expect(assistantTurn).not.toContain('<time>{timestampLabel}</time>');
    expect(assistantTurn).toContain('max-w-[72ch]');
    expect(assistantTurn).not.toContain('data-chat-assistant-loading-row="true"');
    expect(assistantTurn).not.toContain("import { Loader2 } from 'lucide-react';");
    expect(assistantTurn).not.toContain("t('chat.preparingResponse')");
    expect(assistantTurn).not.toContain("t('chat.analyzing')");
    expect(assistantTurn).not.toContain("t('chat.startingAssistant')");
    expect(userMessageTurn).toContain("isEditing ? 'w-[min(42rem,88%)]' : 'max-w-[min(42rem,88%)]'");
    expect(userMessageTurn).toContain(
      'className="rounded-lg border border-ui-text-muted/20 bg-ui-text px-4 py-3 text-sm font-medium text-ui-bg shadow-sm sm:px-5 sm:py-4"'
    );
    expect(chatView).not.toContain("max-w-[min(48rem,94%)] border border-ui-border bg-ui-surface text-ui-text");
    expect(chatView).not.toContain('AnimatePresence mode="popLayout"');
    expect(chatView).not.toContain('layout="position"');
    expect(chatView).not.toContain('<motion.div\n                    key={message.id}');
    expect(enLocale).toContain("conversationHistory: 'Conversation History'");
    expect(enLocale).toContain("showHistory: 'Show conversation history'");
    expect(enLocale).toContain("hideHistory: 'Hide conversation history'");
    expect(enLocale).toContain("newConversation: 'New Conversation'");
    expect(enLocale).toContain("runCancelledMessage: 'Run cancelled. You can send another message when ready.'");
    expect(conversationHistory).toContain('AssistantNavStatusIndicator');
    expect(conversationHistory).toContain('sessionAssistantStatuses?: Record<string, AssistantNavStatus>');
    expect(conversationHistory).toContain("t(`app.aiAssistantStatus.${assistantStatus}`)");
    expect(conversationHistory).not.toContain('>Live<');
    expect(chatView).toContain('sessionAssistantStatuses = {}');
    expect(appClusterChatRuntime).toContain('useConversationAssistantStatuses({');
    expect(appClusterChatRuntime).toContain('isChatVisible: isChatActive');
    expect(appClusterChatRuntime).toContain('sessionAssistantStatuses');
    expect(conversationAssistantStatuses).toContain('const [completedSessionStatusIds, setCompletedSessionStatusIds] = useState<Set<string>>(() => new Set());');
    expect(conversationAssistantStatuses).toContain('const previousSessionStatusesRef = useRef<Map<string, AssistantNavStatus>>(new Map());');
    expect(conversationAssistantStatuses).toContain('const isUnseenSession = !isChatVisible || session.id !== activeSessionId;');
    expect(conversationAssistantStatuses).toContain('isActiveAssistantStatus(previousStatus) && isUnseenSession');
    expect(conversationAssistantStatuses).toContain("completedSessionStatusIds.has(session.id)");
    expect(conversationAssistantStatuses).toContain("rawStatus === 'done'");
    expect(chatView).toContain('Plus');
    expect(chatView).toContain('type-route-title');
    expect(chatView).toContain('type-body mt-2 max-w-2xl');
    expect(chatView).toContain('t(resolvedDescriptionKey, { name: cluster.name })');
    expect(chatView).toContain("const resolvedTitleKey = titleKey || 'chat.triageConsole';");
    expect(chatView).toContain('const title = activeSession && (activeSession.backendSessionId || activeSession.messages.length > 0) ? activeSession.name : t(resolvedTitleKey);');
    expect(chatView).toContain('const isHydratingExistingConversation = Boolean(activeSession?.backendSessionId && activeSession.hydrated === false && visibleMessages.length === 0);');
    expect(chatView).toContain('const hasConversationLoadError = Boolean(activeSession?.backendSessionId && activeSession.messagesLoadFailed && visibleMessages.length === 0);');
    expect(chatView).toContain('const isLoadingInitialConversation = !activeSession && isSessionsLoading;');
    expect(chatView).toContain('const shouldShowTranscriptSkeleton = visibleMessages.length === 0 && !hasConversationLoadError && (isHydratingExistingConversation || isLoadingInitialConversation);');
    expect(chatView).toContain('ref={transcriptRef}');
    expect(chatView).not.toContain('ref={scrollRef}');
    expect(chatView).toContain('{shouldShowTranscriptSkeleton ? (');
    expect(chatView).toContain('<ChatTranscriptSkeleton isPanel={isPanel} label={t(\'chat.loadingConversation\')} />');
    expect(chatView).toContain('<ChatTranscriptLoadError');
    expect(chatSessionSync).toContain('const sessionListKey = `${cluster.workspaceId}:${cluster.id}`;');
    expect(chatSessionSync).toContain('const [isSessionListRequestInFlight, setIsSessionListRequestInFlight] = useState(true);');
    expect(chatSessionSync).toContain('const [loadedSessionListKey, setLoadedSessionListKey] = useState<string | null>(null);');
    expect(chatSessionSync).toContain('const isSessionsLoading = isSessionListRequestInFlight || loadedSessionListKey !== sessionListKey;');
    expect(chatSessionSync).toContain('const activeHydrationSession = sessions.find((item) => item.id === activeSessionId) || null;');
    expect(chatSessionSync).toContain('const activeHydrationSessionKey = activeHydrationSession');
    expect(chatSessionSync).toContain('setLoadedSessionListKey(sessionListKey);');
    expect(chatSessionSync).toContain('messagesLoadFailed: existing?.messagesLoadFailed');
    expect(chatSessionSync).toContain('if (session.messagesLoadFailed)');
    expect(chatSessionSync).not.toContain('activeHydrationRunSignature');
    expect(chatSessionSync).toContain('Run-id churn is intentionally excluded');
    expect(chatSessionSync).toContain('const needsRunTraceHydration = hasRunMessageWithoutTraceDetails(session.messages, runTracesByRunIdRef.current || {});');
    expect(chatSessionSync).toContain('if (session.hydrated && !hasTransientAssistantPlaceholder && !hasAssistantWithInProgressTrace && !needsRunTraceHydration)');
    expect(chatSessionSync).toContain('const currentSessionForMerge =');
    expect(chatSessionSync).toContain('latestSessionsRef.current.find((item) => item.id === session.id) || session;');
    expect(chatSessionSync).toContain('if (currentSessionForMerge.backendSessionId !== backendSessionId)');
    expect(chatSessionSync).toContain('localMessages: currentSessionForMerge.messages,');
    expect(chatSessionSync).toContain('...currentSessionForMerge,');
    expect(chatSessionSync).toContain('activeHydrationSessionKey,');
    expect(chatSessionSync).not.toContain('\n    sessions,\n    setRunTracesByRunId');
    expect(chatSessionSync).toContain('messagesLoadFailed: false');
    expect(chatSessionSync).toContain('messagesLoadFailed: true');
    expect(chatView).toContain('<ChatEmptyPrompt');
    expect(chatTranscriptStates).toContain('export function ChatTranscriptSkeleton');
    expect(chatTranscriptStates).toContain("import { motion, useReducedMotion } from 'framer-motion';");
    expect(chatTranscriptStates).toContain('const shouldReduceMotion = useReducedMotion();');
    expect(chatTranscriptStates).toContain('initial={shouldReduceMotion ? false : { opacity: 0, y: 6 }}');
    expect(chatTranscriptStates).toContain('animate={shouldReduceMotion ? undefined : { opacity: 1, y: 0 }}');
    expect(chatTranscriptStates).toContain('aria-busy="true"');
    expect(chatTranscriptStates).toContain('motion-reduce:animate-none');
    expect(chatTranscriptStates).toContain('export function ChatTranscriptLoadError');
    expect(chatTranscriptStates).toContain('AlertCircle');
    expect(chatTranscriptStates).toContain('export function ChatEmptyPrompt');
    expect(chatTranscriptStates).toContain('suggestions: Array<{ key: string; label: string }>;');
    expect(chatTranscriptStates).toContain('key={suggestion.key}');
    expect(chatTranscriptStates).toContain('BotMessageSquare');
    expect(enLocale).toContain("loadingConversation: 'Loading conversation'");
    expect(enLocale).toContain("conversationLoadFailed: 'Conversation could not be loaded'");
    expect(zhLocale).toContain("loadingConversation: '正在加载会话'");
    expect(zhLocale).toContain("conversationLoadFailed: '无法加载会话'");
    expect(chatView).toContain("variant=\"secondary\"");
    expect(chatView).toContain('const newChatUnavailableReason =');
    expect(chatView).toContain('Tooltip content={newChatUnavailableReason}');
    expect(chatView).toContain('disabled={!canChat}');
    expect(chatView).not.toContain('disabled={!canChat || isRunActive}');
    expect(chatView).toContain('composerActionLabel');
    expect(chatView).toContain('canCancelActiveRun');
    expect(chatView).toContain("type={isRunActive ? 'button' : 'submit'}");
    expect(chatView).toContain('Square');
    expect(chatView).toContain('focus-visible:ring-status-danger/20');
    expect(chatView).toContain('rounded-[1.375rem]');
    expect(chatView).toContain('rows={1}');
    expect(chatView).toContain('min-h-10 text-sm');
    expect(chatView).toContain('composerRootRef');
    expect(chatView).toContain('composerTextareaRef');
    expect(chatView).toContain('previousIsRunActiveRef');
    expect(chatView).toContain('pendingComposerFocusRef');
    expect(chatView).toContain('const requestComposerFocus = () => {');
    expect(chatView).toContain('pendingComposerFocusRef.current = true;');
    expect(chatView).toContain('if (focusComposer()) pendingComposerFocusRef.current = false;');
    expect(chatView).toContain('!pendingComposerFocusRef.current || !canPost || isRunActive');
    expect(chatView).toContain("focus({ preventScroll: true })");
    expect(chatView).toContain('!wasRunActive || isRunActive || !canPost');
    expect(chatView).toContain('composerRootRef.current?.contains(activeElement)');
    expect(chatView).toContain('textarea.style.height =');
    expect(chatView).toContain("aria-label={t('chat.composerInputLabel', { name: cluster.name })}");
    expect(chatView).toContain('role="list" aria-label={t(\'chat.attachments\')}');
    expect(chatView).toContain('role="listitem"');
    expect(chatView).toContain('const modelMenuId = React.useId();');
    expect(chatView).toContain('id={modelSelectorId}');
    expect(chatView).toContain('aria-controls={modelMenuPanelId}');
    expect(chatView).toContain('role="group"');
    expect(chatView).toContain('aria-labelledby={modelSelectorId}');
    expect(chatView).toContain('aria-controls={modelSubmenuPanelId}');
    expect(chatView).toContain('aria-labelledby={modelSubmenuButtonId}');
    expect(chatView).toContain('className="absolute bottom-full right-0 z-50 mb-3 w-64');
    expect(chatView).toContain('sm:right-[calc(100%+0.5rem)]');
    expect(chatView).not.toContain('sm:left-[calc(100%+0.5rem)]');
    expect(chatView).toContain('controlPlaneApi.getWorkspaceAiSettings(cluster.workspaceId)');
    expect(chatView).toContain('buildComposerModelOptions(workspaceAiSettings)');
    expect(chatView).toContain('function modelsForProvider(settings: WorkspaceAiSettings, provider: LlmProvider): string[]');
    expect(chatView).toContain('return settings.allowedProviderModels[provider] || [];');
    expect(chatView).not.toContain('modelBelongsToProvider');
    expect(chatView).toContain('ready: configured && enabled');
    expect(chatView).toContain('const selectableComposerModelOptions = React.useMemo');
    expect(chatView).toContain('composerModelOptions: selectableComposerModelOptions');
    expect(chatView).toContain('const effectiveRecentActivityWarning = recentActivityWarning && (activeSessionId || recentActivityWarning.actionSessionId) ? recentActivityWarning : null;');
    expect(chatView).toContain('const canPost = canChat && isConversationOwner && !effectiveRecentActivityWarning;');
    expect(chatView).toContain('const isComposerRuntimeBlocked = Boolean(workspaceAiSettings && !hasReadyComposerModel);');
    expect(chatView).toContain('resolveAiSettingsGateReason(canChat, isWorkspaceAiSettingsLoading, workspaceAiSettingsError, isComposerRuntimeBlocked)');
    expect(chatView).toContain('const isComposerRuntimeUnavailable = Boolean(isWorkspaceAiSettingsLoading || workspaceAiSettingsError || (workspaceAiSettings && !selectedModelOption?.ready));');
    expect(chatView).toContain('max-h-[min(24rem,calc(100vh-8rem))]');
    expect(chatView).toContain('overflow-y-auto');
    expect(chatView).toContain('composerModelOptions.length > 0 ? `${selectedModelLabel} ${selectedEffortLabel}` : selectedModelLabel');
    expect(chatView).not.toContain('disabled={!option.ready}');
    expect(chatView).not.toContain("t('workspaceAiSettings.providerDisabled')");
    expect(chatView).not.toContain("t('workspaceAiSettings.credentialMissingBadge')");
    expect(chatView).toContain('const selectedEffortTouchedRef = React.useRef(false);');
    expect(chatView).toContain('selectedEffortTouchedRef.current = true;');
    expect(chatView).toContain('selectedEffortTouchedRef.current = false;');
    expect(chatView).toContain('resolveComposerReasoningEffort(workspaceAiSettings, selectedEffort, selectedEffortTouchedRef.current)');
    expect(chatView).toContain('export function resolveComposerReasoningEffort(');
    expect(chatView).toContain('settings.allowedReasoningEfforts.includes(settings.reasoningEffort)');
    expect(chatView).toContain('selectedEffortTouched && settings.allowedReasoningEfforts.includes(selectedEffort)');
    expect(chatView).toContain('!canPost || !hasComposerSubmitPayload || isComposerRuntimeUnavailable');
    expect(chatView).toContain('findComposerModelOption(composerModelOptions, selectedProvider, selectedModel)');
    expect(chatView).toContain('const composerRuntimeSelection: ChatRuntimeSelection | undefined');
    expect(chatView).toContain('const sendText = async (text: string) => {');
    expect(chatView).toContain('const message = buildPromptWithComposerContext(text, composerAttachments);');
    expect(chatView).toContain('const isComposerSubmittingRef = React.useRef(false);');
    expect(chatView).toContain('isComposerRuntimeUnavailable || isComposerSubmittingRef.current');
    expect(chatView).toContain('const releaseComposerSubmitLockSoon = () => {');
    expect(chatView).toContain('setTimeout(() => {');
    expect(chatView).toContain('isComposerSubmittingRef.current = true;');
    expect(chatView).toContain('const sendPromise = onSend(message, composerRuntimeSelection);');
    expect(chatView).toContain('releaseComposerSubmitLockSoon();');
    expect(chatView).toContain('isComposerSubmittingRef.current = false;');
    expect(chatView).toContain('await sendPromise;');
    expect(chatTranscriptStates).toContain('onSendSuggestion: (suggestion: string) => void | Promise<void>;');
    expect(chatTranscriptStates).toContain('type="button"');
    expect(chatView).toContain('canSendSuggestion={canPost && !isRunActive && !isComposerRuntimeUnavailable}');
    expect(chatView).toContain("t('chat.modelLoading')");
    expect(chatView).toContain("isWorkspaceAiSettingsLoading\n      ? t('chat.modelLoading')");
    expect(chatView).toContain("t('chat.modelDefault')");
    expect(chatView).toContain("t('chat.modelUnavailable')");
    expect(chatView).toContain("t('chat.noConfiguredModels')");
    expect(chatView).toContain('aria-pressed={isSelected}');
    expect(chatView).not.toContain('role="menuitemradio"');
    expect(chatView).not.toContain('role="menu"');
    expect(chatView).toContain("t('chat.dropFilesTitle')");
    expect(chatView).toContain('MAX_ATTACHMENT_FILE_BYTES');
    expect(chatView).toContain('MAX_TOTAL_ATTACHMENT_CONTEXT_CHARS');
    expect(chatView).toContain('MAX_COMPOSER_ATTACHMENTS');
    expect(chatView).toContain('Note: content was truncated to fit the message context budget.');
    expect(chatView).toContain("if (dotIndex <= 0 || dotIndex === fileName.length - 1) return '';");
    expect(chatView).toContain('function markdownFenceFor(content: string): string');
    expect(chatView).toContain('while (content.includes(fence))');
    expect(chatView).toContain('const fence = markdownFenceFor(attachment.content);');
    expect(chatView).toContain("t('chat.attachmentTooLargeNotice'");
    expect(chatView).toContain("t('chat.attachmentLimitNotice'");
    expect(chatView).toContain('function fitAttachmentToRemainingContext(attachment: ComposerAttachment, remainingContextChars: number): ComposerAttachment');
    expect(chatView).toContain('const composerAttachmentEpochRef = React.useRef(0);');
    expect(chatView).toContain('const previousActiveSessionIdRef = React.useRef(activeSessionId);');
    expect(chatView).toContain('const availableSlots = Math.max(0, MAX_COMPOSER_ATTACHMENTS - current.length);');
    expect(chatView).toContain('MAX_TOTAL_ATTACHMENT_CONTEXT_CHARS - current.reduce((total, attachment) => total + attachment.content.length, 0)');
    expect(chatView).toContain('const attachmentEpoch = composerAttachmentEpochRef.current;');
    expect(chatView).toContain('if (!isMountedRef.current || attachmentEpoch !== composerAttachmentEpochRef.current) {');
    expect(chatView).toContain('nextAttachments.slice(availableSlots).forEach(revokeAttachmentPreview);');
    expect(chatView).toContain('composerAttachmentEpochRef.current += 1;');
    expect(chatView).toContain('if (previousActiveSessionIdRef.current === activeSessionId) return;');
    expect(chatView).toContain('isMountedRef.current = true;');
    expect(chatView).toContain('isMountedRef.current = false;');
    expect(enLocale).toContain("dropFilesBody: 'Drop files anywhere in this chat window.'");
    expect(enLocale).toContain("composerInputLabel: 'Message {{name}} assistant'");
    expect(enLocale).toContain("footerApprovalRequired: 'Read operations can run automatically. Write actions require explicit approval before execution.'");
    expect(enLocale).toContain("footerApprovalNotRequired: 'Read and write operations can run automatically under this cluster policy.'");
    expect(zhLocale).toContain("footerApprovalRequired: '只读操作可自动执行。写操作必须经过明确批准后才会执行。'");
    expect(zhLocale).toContain("footerApprovalNotRequired: '根据此集群策略，只读和写操作都可以自动执行。'");
    expect(enLocale).toContain('noConfiguredModels');
    expect(enLocale).toContain('attachmentTooLargeNotice');
    expect(chatView).toContain('handleChatWindowDragEnter');
    expect(chatView).toContain('onDragEnter={handleChatWindowDragEnter}');
    expect(chatView).toContain('onDrop={(event) => void handleChatWindowDrop(event)}');
    expect(chatView).not.toContain("aria-label={t('chat.closeHistory')}");
    expect(chatView).toContain("import { UserMessageTurn }");
    expect(userMessageTurn).toContain("import { MessageActions }");
    expect(userMessageTurn).toContain('className="group flex w-full justify-end"');
    expect(userMessageTurn).toContain("aria-label={t('chat.roleUser')}");
    expect(userMessageTurn).toContain('<span className="sr-only">{t(\'chat.roleUser\')}</span>');
    expect(userMessageTurn).toContain('align="right"');
    expect(userMessageTurn).toContain('copyText={message.content}');
    expect(userMessageTurn).toContain('timestampLabel={timestampLabel}');
    expect(userMessageTurn).toContain('{!isEditing && (');
    expect(chatView).toContain('const lastUserMessageIndex = React.useMemo(() => {');
    expect(chatView).toContain('const userTurnRunIdsByIndex = React.useMemo(() => {');
    expect(chatView).toContain('runIdsByIndex.set(index, message.runId || currentTurnRunId);');
    expect(chatView).toContain('const userTurnRunId = userTurnRunIdsByIndex.get(messageIndex);');
    expect(chatView).not.toContain('visibleMessages.findIndex((candidate, candidateIndex)');
    expect(chatView).not.toContain('visibleMessages.slice(messageIndex, turnEndIndex)');
    expect(chatView).toContain('const startEditingMessage = (messageId: string, content: string) => {');
    expect(chatView).toContain('const submitEditedMessage = async (messageId: string) => {');
    expect(chatView).toContain('if (!nextContent || !canPost || isSubmittingEdit || isRunActive || isComposerRuntimeUnavailable) return;');
    expect(chatView).toContain('await onEditLastUserMessage(messageId, nextContent, composerRuntimeSelection);');
    expect(chatView).toContain('!isComposerRuntimeUnavailable &&');
    expect(chatView).toContain("userTurnTrace?.status === 'cancelled' || userTurnTrace?.status === 'failed'");
    expect(chatView).toContain('messageIndex === lastUserMessageIndex');
    expect(chatView).toContain('<UserMessageTurn');
    expect(chatView).toContain('canEdit={canEditUserMessage}');
    expect(userMessageTurn).toContain('onEdit={canEdit ? onStartEdit : undefined}');
    expect(userMessageTurn).toContain('<textarea');
    expect(userMessageTurn).toContain('const textareaRef = React.useRef<HTMLTextAreaElement>(null);');
    expect(userMessageTurn).toContain('textarea.setSelectionRange(selectionEnd, selectionEnd);');
    expect(userMessageTurn).toContain('}, [isEditing]);');
    expect(userMessageTurn).toContain("aria-label={t('chat.editMessage')}");
    expect(userMessageTurn).toContain("{t('chat.saveEdit')}");
    expect(userMessageTurn).toContain("{t('chat.cancelEdit')}");
    expect(chatView).not.toContain('<span>{t(\'chat.roleUser\')}</span>');
    expect(chatView).not.toContain('<span>{formatMessageTime(message.timestamp)}</span>');
    expect(chatGateDialog).toContain('role="dialog"');
    expect(chatGateDialog).toContain('const hasRecentActivityAction = Boolean(recentActivityWarning && (activeSessionId || actionSessionId));');
    expect(chatGateDialog).toContain('const recentActivityBody = recentActivityWarning?.message.trim();');
    expect(chatGateDialog).toContain('const recentActivityActionLabel = recentActivityWarning?.actionLabel?.trim();');
    expect(chatGateDialog).toContain('const hasDialogAction = recentActivityWarning ? hasRecentActivityAction : canManageAiSettings;');
    expect(chatGateDialog).toContain('aria-modal={hasDialogAction ? true : undefined}');
    expect(chatGateDialog).toContain('const primaryActionRef = React.useRef<HTMLButtonElement>(null);');
    expect(chatGateDialog).toContain('const shouldReduceMotion = useReducedMotion();');
    expect(chatGateDialog).toContain('const restoreTarget = document.activeElement instanceof HTMLElement ? document.activeElement : null;');
    expect(chatGateDialog).toContain('const primaryAction = primaryActionRef.current;');
    expect(chatGateDialog).toContain('if (primaryAction && !primaryAction.disabled)');
    expect(chatGateDialog).toContain('primaryAction.focus({ preventScroll: true });');
    expect(chatGateDialog).toContain('dialogRef.current?.focus({ preventScroll: true });');
    expect(chatGateDialog).toContain('restoreTarget.focus({ preventScroll: true });');
    expect(chatGateDialog).toContain('Boolean(recentActivityWarning)');
    expect(chatGateDialog).toContain('tabIndex={-1}');
    expect(chatGateDialog).toContain('initial={shouldReduceMotion ? false : { opacity: 0 }}');
    expect(chatGateDialog).toContain('initial={shouldReduceMotion ? false : { opacity: 0, y: 10, scale: 0.98 }}');
    expect(chatGateDialog).toContain('bg-ui-bg/70 p-4 backdrop-blur-sm');
    expect(chatGateDialog).toContain('rounded-lg border border-ui-border bg-ui-surface');
    expect(chatGateDialog).toContain("t('chat.recentActivityActionTitle')");
    expect(chatGateDialog).toContain("recentActivityBody || t('chat.chooseRecentActivityAction')");
    expect(chatGateDialog).toContain("t('chat.aiSettingsRequiredTitle')");
    expect(chatGateDialog).toContain("t('chat.aiSettingsRequiredManageBody')");
    expect(chatGateDialog).toContain("t('chat.aiSettingsUnavailableManageBody')");
    expect(chatGateDialog).toContain("t('chat.aiSettingsRequiredReadOnlyBody')");
    expect(chatGateDialog).toContain('const handleDialogKeyDown = (event: React.KeyboardEvent<HTMLElement>) => {');
    expect(chatGateDialog).toContain("if (event.key !== 'Tab' || !hasDialogAction) return;");
    expect(chatGateDialog).toContain('dialog.querySelectorAll<HTMLElement>(focusableSelector)');
    expect(chatGateDialog).toContain("element.getAttribute('aria-hidden') === 'true'");
    expect(chatGateDialog).toContain('window.getComputedStyle(element)');
    expect(chatGateDialog).toContain('getDialogFocusWrapIndex({');
    expect(chatGateDialog).toContain('focusableElements.findIndex((element) => element === document.activeElement)');
    expect(chatGateDialog).toContain('(focusableElements[targetIndex] || dialog).focus({ preventScroll: true });');
    expect(chatGateDialog).toContain('onClick={onOpenAiSettings}');
    expect(chatGateDialog).toContain('onOpenRecentActivitySession(actionSessionId)');
    expect(chatGateDialog).toContain("recentActivityActionLabel || t('chat.openConversation')");
    expect(chatGateDialog).toContain('if (activeSessionId) onDismissRecentActivityWarning(activeSessionId);');
    expect(chatGateDialog).not.toContain('translate-y-[calc(100%+0.75rem)]');
    expect(chatView).toContain('const hasBlockingGate = Boolean(recentActivityWarning || aiSettingsGateReason);');
    expect(chatView).toContain("content.setAttribute('inert', '')");
    expect(chatView).toContain('aria-hidden={hasBlockingGate ? true : undefined}');
    expect(chatView).toContain('recentActivityWarning: effectiveRecentActivityWarning');
    expect(chatView).toContain("const blockedComposerMessage = recentActivityWarning");
    expect(chatView).toContain("t('chat.chooseRecentActivityAction')");
    expect(chatView).toContain('placeholder={canPost ? t(resolvedInputPlaceholderKey, { name: cluster.name }) : blockedComposerMessage}');
    expect(chatView).toContain('{canPost ? composerSubmitUnavailableReason || t(resolvedFooterKey) : blockedFooterMessage}');
    expect(chatView).toContain("recentActivityWarning ? t('chat.chooseRecentActivityAction')");
    expect(chatView).toContain('const activeRunTrace = isInFlightPlaceholder && activeRunId ? runTracesByRunId[activeRunId] : undefined;');
    expect(chatView).toContain('const trace = activeRunTrace || messageTrace;');
    expect(chatView).toContain('const traceRunId = trace?.runId || message.runId || message.id;');
    expect(chatView).toContain("const messageKey = !isUser && previousMessage?.role === 'user' ? `assistant-turn-${previousMessage.id}` : message.id;");
    expect(chatView).toContain('const hasLaterUserMessage = messageIndex < lastUserMessageIndex;');
    expect(chatView).toContain('const isStaleCancelledAssistantStatus =');
    expect(chatView).toContain("traceToRender?.status === 'cancelled'");
    expect(chatView).toContain('<div key={messageKey} className="flex w-full justify-start">');
    expect(chatView).toContain('compactStatusOnly={isStaleCancelledAssistantStatus}');
    expect(chatView).toContain("label: 'Preparing response'");
    expect(chatView).toContain("detail: 'Waiting for the first progress update.'");
    expect(assistantTurn).toContain("import { motion, type Transition, useReducedMotion } from 'framer-motion';");
    expect(assistantTurn).toContain('const shouldReduceMotion = useReducedMotion();');
    expect(assistantTurn).toContain("const previousWorkingTextRef = React.useRef('');");
    expect(assistantTurn).toContain("const isTraceInProgress = trace?.status === 'connecting' || trace?.status === 'running';");
    expect(assistantTurn).toContain('const isAssistantWorking = isInFlightPlaceholder || isTraceInProgress;');
    expect(assistantTurn).toContain("const inlineWorkingText = activeReasoningSummary || (isAssistantWorking ? t('chat.thinking') : '');");
    expect(assistantTurn).toContain('const previousWorkingText = previousWorkingTextRef.current;');
    expect(assistantTurn).toContain('const stableWorkingText = previousWorkingText && inlineWorkingText.startsWith(previousWorkingText)');
    expect(assistantTurn).toContain('const incomingWorkingText = stableWorkingText');
    expect(assistantTurn).toContain('const shouldAnimateIncomingText = Boolean(inlineWorkingText && incomingWorkingText);');
    expect(assistantTurn).toContain('const incomingTextInitial = shouldReduceMotion');
    expect(assistantTurn).toContain('? { opacity: 0.78 }');
    expect(assistantTurn).toContain(': { opacity: 0.38 };');
    expect(assistantTurn).toContain('const incomingTextAnimate = { opacity: 1 };');
    expect(assistantTurn).toContain('const incomingTextTransition: Transition = shouldReduceMotion');
    expect(assistantTurn).toContain('? { duration: 0.14, ease: [0.16, 1, 0.3, 1] }');
    expect(assistantTurn).toContain(': { duration: 0.24, ease: [0.16, 1, 0.3, 1] };');
    expect(assistantTurn).toContain('const shouldShowWorkingShimmer = Boolean(inlineWorkingText && isAssistantWorking && shouldReduceMotion !== true);');
    expect(assistantTurn).toContain('const workingShimmerDurationSeconds = activeReasoningSummary ? 5 : 3.8;');
    expect(assistantTurn).toContain('previousWorkingTextRef.current = inlineWorkingText;');
    expect(assistantTurn).toContain(".replace(/\\*\\*(.*?)\\*\\*/g, '$1')");
    expect(assistantTurn).toContain('const workingLine = inlineWorkingText ? (');
    expect(assistantTurn).toContain("const assistantColumnClass = 'w-full max-w-[72ch]';");
    expect(assistantTurn).toContain("isInFlightPlaceholder ? `flex min-h-8 items-center ${assistantColumnClass}` : `mt-4 border-t border-ui-border/80 pt-2 ${assistantColumnClass}`");
    expect(assistantTurn).toContain('const copyText = content.trim() || inlineWorkingText;');
    expect(assistantTurn).not.toContain("t('chat.reasoningSummary')");
    expect(assistantTurn).not.toContain('type-micro-label mb-2 text-ui-text-muted');
    expect(assistantTurn).toContain('type-caption relative block truncate text-ui-text-muted');
    expect(assistantTurn).toContain("shouldShowWorkingShimmer ? 'reasoning-summary-active' : ''");
    expect(assistantTurn).toContain('<span>{stableWorkingText}</span>');
    expect(assistantTurn).toContain('title={inlineWorkingText}');
    expect(assistantTurn).toContain('aria-live="polite"');
    expect(assistantTurn).toContain("'--reasoning-summary-shimmer-duration': `${workingShimmerDurationSeconds}s`");
    expect(assistantTurn).not.toContain('WebkitLineClamp: 2');
    expect(assistantTurn).not.toContain("display: '-webkit-box'");
    expect(assistantTurn).toContain('<motion.span');
    expect(assistantTurn).toContain('key={inlineWorkingText}');
    expect(assistantTurn).not.toContain("className={shouldShowWorkingShimmer ? 'reasoning-summary-active' : undefined}");
    expect(assistantTurn).toContain('initial={incomingTextInitial}');
    expect(assistantTurn).toContain('animate={incomingTextAnimate}');
    expect(assistantTurn).toContain('transition={incomingTextTransition}');
    expect(assistantTurn).toContain('{stableWorkingText}');
    expect(assistantTurn).toContain('{incomingWorkingText}');
    expect(assistantTurn).toContain('<span>{inlineWorkingText}</span>');
    expect(assistantTurn).not.toContain("activeReasoningSummary ? 'text-ui-text' : 'text-ui-text-muted'");
    expect(assistantTurn).toContain('</motion.span>');
    expect(assistantTurn).toContain('compactStatusOnly?: boolean;');
    expect(assistantTurn).toContain('compactStatusOnly = false');
    expect(assistantTurn).toContain('const shouldRenderCompactStatusOnly = compactStatusOnly && hasTraceDetails;');
    expect(assistantTurn).toContain('{isInFlightPlaceholder ? workingLine : shouldRenderCompactStatusOnly ? null : (');
    expect(assistantTurn).toContain('{!isInFlightPlaceholder && workingLine}');
    expect(assistantTurn).toContain('<MessageActions');
    expect(assistantTurn).toContain('align="left"');
    expect(assistantTurn).toContain('copyText={copyText}');
    expect(assistantTurn).toContain('timestampLabel={timestampLabel}');
    expect(assistantTurn).toContain('const messageActions = (');
    expect(assistantTurn).toContain('const hasTraceDetails = Boolean(');
    expect(assistantTurn).toContain('trace.steps.length > 0 ||');
    expect(assistantTurn).toContain('trace.toolCalls.length > 0 ||');
    expect(assistantTurn).toContain('(trace.skillLoads?.length || 0) > 0 ||');
    expect(assistantTurn).toContain('(trace.reasoningSummaries?.length || 0) > 0 ||');
    expect(assistantTurn).toContain('(trace.timelineEvents?.length || 0) > 0');
    expect(assistantTurn).toContain('{!hasTraceDetails && !shouldRenderCompactStatusOnly && messageActions}');
    expect(assistantTurn).toContain('compactStatusOnly={shouldRenderCompactStatusOnly}');
    expect(assistantTurn).toContain('{hasTraceDetails && !shouldRenderCompactStatusOnly && messageActions}');
    expect(assistantTurn).not.toContain('<motion.p');
    expect(assistantTurn).not.toContain('initial={shouldReduceMotion ? false : { opacity: 0.28, y: 2 }}');
    expect(assistantTurn).not.toContain('rounded-md border border-ui-border bg-ui-surface/45 px-3 py-2');
    expect(assistantTurn).toContain('suppressCompactReasoningSummary={Boolean(inlineWorkingText)}');
    expect(messageActions).toContain("import { Check, Copy, Pencil } from 'lucide-react';");
    expect(messageActions).toContain("align: 'left' | 'right';");
    expect(messageActions).toContain('onEdit?: () => void;');
    expect(messageActions).toContain('const copyResetTimeoutRef = React.useRef<number | null>(null);');
    expect(messageActions).toContain('}, [copyText]);');
    expect(messageActions).toContain('window.clearTimeout(copyResetTimeoutRef.current);');
    expect(messageActions).toContain("const canUseClipboard = typeof navigator !== 'undefined' && Boolean(navigator.clipboard?.writeText);");
    expect(messageActions).toContain('disabled={!canCopyToClipboard}');
    expect(messageActions).toContain('await navigator.clipboard.writeText(copyText);');
    expect(messageActions).toContain('copyResetTimeoutRef.current = window.setTimeout(() => {');
    expect(messageActions).toContain('} catch {');
    expect(messageActions).toContain('group-hover:opacity-100 group-focus-within:opacity-100');
    expect(messageActions).toContain('<time>{timestampLabel}</time>');
    expect(messageActions).toContain("aria-label={t('chat.editMessage')}");
    expect(messageActions).toContain('<Pencil className="h-3.5 w-3.5" />');
    expect(messageActions).toContain("aria-label={hasCopied ? t('chat.copiedMessage') : t('chat.copyMessage')}");
    expect(messageActions).toContain("align === 'right' ? 'justify-end text-ui-text-muted' : 'justify-start'");
    expect(styles).toContain('.reasoning-summary-active {');
    expect(styles).toContain('animation: reasoning-summary-text-sheen var(--reasoning-summary-shimmer-duration, 3.8s) cubic-bezier(0.22, 1, 0.36, 1) infinite;');
    expect(styles).toContain('rgb(var(--brand-orange-bright-rgb) / 0.52)');
    expect(styles).toContain('-webkit-background-clip: text;');
    expect(styles).toContain('-webkit-text-fill-color: transparent;');
    expect(styles).toContain('@keyframes reasoning-summary-text-sheen');
    expect(styles).toContain('-webkit-text-fill-color: currentColor;');
    expect(styles).not.toContain('.reasoning-summary-active::after');
    expect(traceFooter).toContain('aria-expanded={isExpanded}');
    expect(traceFooter).toContain('aria-controls={contentId}');
    expect(traceFooter).not.toContain('AnimatePresence initial={false} mode="wait"');
    expect(traceFooter).toContain('RunTraceTimelineEvent');
    expect(traceFooter).toContain('BookOpen, ChevronRight, CircleDashed, MessageSquare, Wrench');
    expect(traceFooter).toContain('Skill context · Loaded');
    expect(traceFooter).not.toContain('ChevronDown');
    expect(traceFooter).toContain("function inferTimelineStepType(label: string): RunTraceTimelineEvent['type']");
    expect(traceFooter).toContain("if (label.startsWith('Skill context ') || label.startsWith('Loading skill context:')) return 'skill';");
    expect(traceFooter).toContain("return label.startsWith('Tool call ') || label.startsWith('Approval ') ? 'tool' : 'step';");
    expect(traceFooter).toContain("function inferTimelineToolStatus(toolCall: LiveRunTrace['toolCalls'][number]): RunTraceTimelineEvent['status']");
    expect(traceFooter).toContain("if (toolCall.status === 'running') return 'info';");
    expect(traceFooter).toContain("return toolCall.isError ? 'error' : 'success';");
    expect(traceFooter).toContain('function buildTimelineEvents(trace: LiveRunTrace): RunTraceTimelineEvent[]');
    expect(traceFooter).toContain('if (trace.timelineEvents?.length)');
    expect(traceFooter).toContain('type: inferTimelineStepType(step.label)');
    expect(traceFooter).toContain("type: 'reasoning' as const");
    expect(traceFooter).toContain("label: summary.status === 'unavailable' ? 'Reasoning summary unavailable' : 'Reasoning summary'");
    expect(traceFooter).toContain('const fallbackToolTimestamp = Math.max(');
    expect(traceFooter).toContain('...trace.toolCalls.map((toolCall, index) => ({');
    expect(traceFooter).toContain('id: toolCall.callId');
    expect(traceFooter).toContain('label: toolCall.tool');
    expect(traceFooter).toContain('status: inferTimelineToolStatus(toolCall)');
    expect(traceFooter).toContain('timestamp: fallbackToolTimestamp + index + 1');
    expect(traceFooter).toContain("].sort((left, right) => left.timestamp - right.timestamp);");
    expect(traceFooter).toContain('function getTimelineEventMeta(event: RunTraceTimelineEvent): string');
    expect(traceFooter).toContain('function getTimelineEventToneClass(event: RunTraceTimelineEvent): string');
    expect(traceFooter).toContain('function getTimelineMarkerClass(event: RunTraceTimelineEvent): string');
    expect(traceFooter).toContain('getTraceActivityLabel(trace)');
    expect(traceFooter).toContain('suppressCompactReasoningSummary?: boolean;');
    expect(traceFooter).toContain('compactStatusOnly?: boolean;');
    expect(traceFooter).toContain('className?: string;');
    expect(traceFooter).toContain('suppressCompactReasoningSummary = false');
    expect(traceFooter).toContain('compactStatusOnly = false');
    expect(traceFooter).toContain('const compactReasoningSummary = isInProgress && !suppressCompactReasoningSummary');
    expect(traceFooter).toContain('const hasCompactReasoningSummary = Boolean(compactReasoningSummary);');
    expect(traceFooter).toContain('const shouldShowCompactStatusLabel = hasCompactReasoningSummary || !isInProgress || !suppressCompactReasoningSummary;');
    expect(traceFooter).toContain("const compactStatusLabel = hasCompactReasoningSummary ? 'Working through' : statusLabel;");
    expect(traceFooter).toContain("const activitySummary = trace.status === 'connecting'");
    expect(traceFooter).toContain("? 'Waiting for progress'");
    expect(traceFooter).toContain('`${trace.steps.length} steps`');
    expect(traceFooter).toContain('`${completedToolCalls} of ${trace.toolCalls.length} function calls complete`');
    expect(traceFooter).toContain("'No function tool calls'");
    expect(traceFooter).toContain("const disclosureLabel = isExpanded ? 'Hide run details' : 'Show run details';");
    expect(traceFooter).toContain('const disclosureSummary = hasCompactReasoningSummary ? compactReasoningSummary : activitySummary;');
    expect(traceFooter).toContain("${compactStatusOnly ? '' : 'mt-3'} w-full ${className || 'max-w-[72ch]'}");
    expect(traceFooter).toContain('group min-h-10 items-center gap-2 py-2 pl-0 pr-2.5');
    expect(traceFooter).toContain('className={`-ml-1 shrink-0 text-ui-text-muted group-hover:text-ui-text');
    expect(traceFooter).toContain("'flex w-full rounded-md bg-ui-surface/45 text-ui-text hover:bg-ui-surface/75'");
    expect(traceFooter).toContain("'flex w-full rounded-md bg-ui-surface/45 text-ui-text-muted hover:bg-ui-surface/75 hover:text-ui-text'");
    expect(traceFooter).not.toContain("'flex w-full rounded-t-md border border-ui-border");
    expect(traceFooter).not.toContain('text-ui-text shadow-sm');
    expect(traceFooter).toContain('{disclosureLabel}');
    expect(traceFooter).toContain('aria-hidden="true"');
    expect(traceFooter).toContain("<ChevronRight className=\"h-4 w-4\" />");
    expect(traceFooter).toContain("shouldReduceMotion");
    expect(traceFooter).toContain('animate-pulse motion-reduce:animate-none');
    expect(traceFooter).toContain("'transition-transform duration-150 ease-out'");
    expect(traceFooter).toContain("${isExpanded ? 'rotate-90' : 'rotate-0'}");
    expect(traceFooter).toMatch(/<ChevronRight className="h-4 w-4" \/>[\s\S]*?<span className=\{`h-2 w-2 shrink-0 rounded-full/);
    expect(traceFooter).not.toContain('{isExpanded ? <ChevronDown');
    expect(traceFooter).toContain('bg-ui-surface/45 text-ui-text-muted hover:bg-ui-surface/75 hover:text-ui-text');
    expect(traceFooter).toContain('shouldShowCompactStatusLabel &&');
    expect(traceFooter).toContain('{compactStatusLabel}');
    expect(traceFooter).toContain('flex min-w-0 max-w-[min(34rem,54vw)] flex-1 items-center gap-1.5');
    expect(traceFooter).toContain('<span className="type-caption shrink-0 text-ui-text-muted/70">·</span>');
    expect(traceFooter).toContain('className={`type-caption min-w-0 truncate ${');
    expect(traceFooter).toContain("? 'text-ui-text'");
    expect(traceFooter).toContain(": 'text-ui-text-muted'");
    expect(traceFooter).toContain('title={disclosureSummary}');
    expect(traceFooter).toContain('{disclosureSummary}');
    expect(traceFooter).toContain('const timelineEvents = buildTimelineEvents(trace);');
    expect(traceFooter).not.toContain('Run timeline');
    expect(traceFooter).toContain('className="mt-1 border-t border-ui-border/80 pt-1"');
    expect(traceFooter).toContain('max-h-80 overflow-hidden');
    expect(traceFooter).not.toContain('bg-ui-bg/70 shadow-sm');
    expect(traceFooter).not.toContain('<p className="type-micro-label truncate text-ui-text-muted" title={activitySummary}>');
    expect(traceFooter).toContain('timelineEvents.map((event)');
    expect(traceFooter).toContain("event.type === 'reasoning'");
    expect(traceFooter).toContain('<MessageSquare className={`h-3.5 w-3.5 ${getTimelineEventToneClass(event)}`} />');
    expect(traceFooter).toContain("event.type === 'tool'");
    expect(traceFooter).toContain('<Wrench className={`h-3.5 w-3.5 ${getTimelineEventToneClass(event)}`} />');
    expect(traceFooter).toContain("if (event.type === 'tool') {");
    expect(traceFooter).toContain("if (event.status === 'success') return 'Function tool · Done';");
    expect(traceFooter).toContain("if (event.status === 'error') return 'Function tool · Attention';");
    expect(traceFooter).toContain("if (event.status === 'info') return 'Function tool · Running';");
    expect(traceFooter).toContain("return 'Function tool';");
    expect(traceFooter).toContain('type-micro-label max-w-[45%] shrink truncate');
    expect(traceFooter).toContain('title={getTimelineEventMeta(event)}');
    expect(traceFooter).toContain('{getTimelineEventMeta(event)}');
    expect(traceFooter).toContain('type-caption mt-0.5 line-clamp-4 whitespace-pre-wrap break-words text-ui-text-muted');
    expect(traceFooter).toContain('title={event.detail}');
    expect(traceFooter).not.toContain('max-h-28 overflow-y-auto overscroll-contain');
    expect(traceFooter).toContain('No run activity has been recorded for this message.');
    expect(traceFooter).not.toContain('mt-2 max-h-80 overflow-hidden rounded-md');
    expect(traceFooter).not.toContain('border border-ui-border bg-ui-bg/80');
    expect(traceFooter).not.toContain('rounded-full px-2 py-0.5');
    expect(traceFooter).toContain('hidden={!isExpanded}');
    expect(traceFooter).toContain('max-h-80 divide-y divide-ui-border overflow-y-auto overscroll-contain');
    expect(traceFooter).toContain('timelineScrollRef');
    expect(traceFooter).toContain('timelineScrollRef.current.scrollTop = timelineScrollRef.current.scrollHeight;');
    expect(traceFooter).toContain('const latestTimelineEventKey = timelineEvents.at(-1)');
    expect(traceFooter).not.toContain('Progress steps');
    expect(traceFooter).not.toContain('Reasoning Summaries');
    expect(traceFooter).not.toContain('Tool Activity');
    expect(traceFooter).not.toContain('Run updates');
    expect(traceFooter).not.toContain('const statusLabel = trace.status');
    expect(markdownComponents).toContain("href?.startsWith('#/')");
    expect(markdownComponents).toContain("target={isInternalRoute ? undefined : '_blank'}");
    expect(markdownComponents).toContain("rel={isInternalRoute ? undefined : 'noreferrer'}");
    expect(assistantTurn).toContain('remarkPlugins={markdownRemarkPlugins}');
    expect(userMessageTurn).toContain('remarkPlugins={markdownRemarkPlugins}');
    expect(enLocale).toContain("thinking: 'Thinking...'");
    expect(enLocale).toContain("copyMessage: 'Copy message'");
    expect(enLocale).toContain("copiedMessage: 'Copied'");
    expect(enLocale).toContain("editMessage: 'Edit message'");
    expect(enLocale).toContain("saveEdit: 'Send'");
    expect(enLocale).toContain("cancelEdit: 'Cancel'");
    expect(zhLocale).toContain("newConversation: '新会话'");
    expect(zhLocale).toContain("thinking: '思考中...'");
    expect(zhLocale).toContain("copyMessage: '复制消息'");
    expect(zhLocale).toContain("copiedMessage: '已复制'");
    expect(zhLocale).toContain("editMessage: '编辑消息'");
    expect(zhLocale).toContain("saveEdit: '发送'");
    expect(zhLocale).toContain("cancelEdit: '取消'");
    const visibleChatStatusSources = `${assistantTurn}\n${chatView}\n${traceFooter}`;
    expect(visibleChatStatusSources).not.toContain('Starting assistant');
    expect(visibleChatStatusSources).not.toContain('run record');
    expect(visibleChatStatusSources).not.toContain('control plane');
    expect(visibleChatStatusSources).not.toContain('execution engine');
    expect(visibleChatStatusSources).not.toContain('reasoning trace');
    expect(useTargetChat).toContain('const handleEditLastUserMessage = async (messageId: string, nextContent: string, runtimeSelection?: ChatRuntimeSelection) => {');
    expect(useTargetChat).toContain('runtimeSelection');
    expect(useTargetChat).toContain("const userIndex = sanitizedMessages.findIndex((message) => message.id === messageId && message.role === 'user');");
    expect(useTargetChat).toContain("trace?.status === 'cancelled' || trace?.status === 'failed' || cancelledRunIdsRef.current.has(runId)");
    expect(useTargetChat).toContain('const revisedSession: ChatSession = {');
    expect(useTargetChat).toContain('messages: sanitizedMessages.slice(0, userIndex)');
    expect(useTargetChat).toContain('overrideInput: prompt');
    expect(chatSubmit).toContain('messages: activeSession.messages');
    expect(chatSubmit).toContain('draftConversationName: string;');
    expect(chatSubmit).toContain('name: draftConversationName,');
    expect(chatSubmit).not.toContain("|| 'New Conversation'");
  });
});
