import type React from 'react';
import type { ActivePrimaryNav, ActiveResourceNav } from '@/app/appRouteState';
import type { ResolvedTheme, ThemePreference } from '@/app/theme';
import type { NavigateOptions as RouterNavigateOptions } from '@/hooks/useAppRouter';
import type { AppLanguageCode, AppLanguageOption } from '@/i18n/languageConfig';
import type { controlPlaneApi as ControlPlaneApi, ControlPlaneVirtualMachine } from '@/services/controlPlaneApi';
import type { AgentAccessMode } from '@/services/control-plane/types';
import type { KubernetesCluster, User, Workspace, WorkspaceInvitation } from '@/types';
import type { AppRoute, ClusterSubview, VmSubview } from '@/utils/routes';

export interface AppShellProps {
  acceptWorkspaceInvitation: (token: string) => Promise<void>;
  activeClusterSubview: ClusterSubview;
  activeVmSubview: VmSubview;
  activePrimaryNav: ActivePrimaryNav;
  activeResourceNav: ActiveResourceNav;
  kubernetesClusters: KubernetesCluster[];
  kubernetesClustersInWorkspaceContext: KubernetesCluster[];
  virtualMachinesInWorkspaceContext: ControlPlaneVirtualMachine[];
  hasLoadedWorkspaceVirtualMachines: boolean;
  clusterContextId: string | undefined;
  clusterCopilotCluster: KubernetesCluster | null;
  clusterCopilotInitialPrompt: { id: number; text: string } | null;
  clusterCopilotWidth: number;
  clusterCopilotWorkspace: Workspace | undefined;
  clusterCreationStep: 'details' | 'instructions';
  clusterInstallCommand: string;
  clusterInstallWarnings: string[];
  deleteTargetWorkspace: Workspace | undefined;
  dismissToast: (id: string) => void;
  excludeNamespaces: string;
  getCurrentUserRoleForWorkspace: (workspaceId: string) => Workspace['members'][number]['role'];
  getWorkspacePermission: (workspaceId: string, permission: keyof NonNullable<Workspace['permissions']>) => boolean;
  handleCancelAddCluster: () => void;
  handleConfirmAddCluster: () => Promise<void>;
  handleCreateWorkspace: (name: string) => Promise<Workspace>;
  handleDeleteCluster: (cluster: KubernetesCluster) => Promise<void>;
  handleDeleteWorkspace: (workspaceId: string) => Promise<void>;
  handleInitiateAddCluster: (workspaceId: string) => void;
  handleLogout: () => Promise<void>;
  handleProceedToInstructions: (agentAccessMode?: AgentAccessMode) => Promise<void>;
  handleSelectWorkspaceContext: (workspaceId: string) => void;
  includeNamespaces: string;
  installAgentCluster: KubernetesCluster | null;
  installAgentWorkspace: Workspace | undefined;
  currentUserEmail: string;
  invitationTokenMissingMessage: string;
  isAddingCluster: boolean;
  isClusterCopilotOpen: boolean;
  isClusterSidebar: boolean;
  isVirtualMachineSidebar: boolean;
  isCreatingCluster: boolean;
  isCreatingWorkspace: boolean;
  isDark: boolean;
  isDeletingWorkspace: boolean;
  isMobileNavOpen: boolean;
  isAccountMenuOpen: boolean;
  isSidebarWorkspaceMenuOpen: boolean;
  language: AppLanguageCode;
  languageOptions: AppLanguageOption[];
  loadWorkspaceInvitation: (token: string) => ReturnType<typeof ControlPlaneApi.getWorkspaceInvitation>;
  navigate: (path: string, options?: RouterNavigateOptions) => void;
  navigateToKubernetesCluster: (cluster: KubernetesCluster) => void;
  newClusterName: string;
  openClusterCopilot: (cluster: KubernetesCluster, prompt?: string) => void;
  onConversationDeleted: (sessionName: string, targetName: string) => void;
  refreshWorkspaceInvitations: (workspaceId: string) => Promise<void>;
  refreshWorkspaceMembers: (workspaceId: string) => Promise<void>;
  route: AppRoute;
  selectedSidebarCluster: KubernetesCluster | null;
  selectedSidebarVm: Pick<ControlPlaneVirtualMachine, 'id' | 'workspaceId' | 'name'> | null;
  selectedWorkspace: Workspace | undefined;
  selectedWorkspaceId: string | null;
  setKubernetesClusters: React.Dispatch<React.SetStateAction<KubernetesCluster[]>>;
  onReplaceWorkspaceVirtualMachines: (workspaceId: string, nextVirtualMachines: ControlPlaneVirtualMachine[]) => void;
  onUpsertWorkspaceVirtualMachine: (workspaceId: string, virtualMachine: ControlPlaneVirtualMachine) => void;
  onRemoveWorkspaceVirtualMachine: (workspaceId: string, virtualMachineId: string) => void;
  setClusterCopilotInitialPrompt: React.Dispatch<React.SetStateAction<{ id: number; text: string } | null>>;
  setClusterCopilotWidth: React.Dispatch<React.SetStateAction<number>>;
  setClusterCreationStep: React.Dispatch<React.SetStateAction<'details' | 'instructions'>>;
  setDeleteWorkspaceId: React.Dispatch<React.SetStateAction<string | null>>;
  setExcludeNamespaces: React.Dispatch<React.SetStateAction<string>>;
  setIncludeNamespaces: React.Dispatch<React.SetStateAction<string>>;
  setInstallAgentClusterId: React.Dispatch<React.SetStateAction<string | null>>;
  setIsAccountMenuOpen: React.Dispatch<React.SetStateAction<boolean>>;
  setIsClusterCopilotOpen: React.Dispatch<React.SetStateAction<boolean>>;
  setIsCreatingWorkspace: React.Dispatch<React.SetStateAction<boolean>>;
  setIsDeletingWorkspace: React.Dispatch<React.SetStateAction<boolean>>;
  setIsMobileNavOpen: React.Dispatch<React.SetStateAction<boolean>>;
  setIsSidebarWorkspaceMenuOpen: React.Dispatch<React.SetStateAction<boolean>>;
  setLanguage: (language: AppLanguageCode) => void;
  setNewClusterName: React.Dispatch<React.SetStateAction<string>>;
  setWorkspaces: React.Dispatch<React.SetStateAction<Workspace[]>>;
  showToast: (message: string) => void;
  sidebarAccountMenuRef: React.RefObject<HTMLDivElement | null>;
  sidebarWorkspaceMenuRef: React.RefObject<HTMLDivElement | null>;
  themePreference: ThemePreference;
  resolvedTheme: ResolvedTheme;
  toasts: Array<{ id: string; message: string }>;
  toWorkspaceInvitation: (invitation: Awaited<ReturnType<typeof ControlPlaneApi.createWorkspaceInvitation>>) => WorkspaceInvitation;
  selectTheme: (preference: ThemePreference, source: HTMLButtonElement) => void;
  updateKubernetesCluster: (clusterId: string, updates: Partial<KubernetesCluster>) => void;
  updateWorkspace: (workspaceId: string, updates: Partial<Workspace>) => void;
  user: User;
  workspaceClusterCounts: Map<string, number>;
  workspaceContext: Workspace | undefined;
  workspaceContextId: string | null;
  workspaces: Workspace[];
}
