import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { describe, expect, it } from 'vitest';

const root = resolve(__dirname, '../../..');
const dashboard = readFileSync(resolve(root, 'src/components/dashboard/Dashboard.tsx'), 'utf8');
const clusterCatalog = readFileSync(resolve(root, 'src/components/dashboard/ClusterCatalog.tsx'), 'utf8');
const clusterTelemetryPanel = readFileSync(resolve(root, 'src/components/dashboard/ClusterTelemetryPanel.tsx'), 'utf8');
const clusterTelemetryModel = readFileSync(resolve(root, 'src/components/dashboard/clusterTelemetryModel.ts'), 'utf8');
const kubernetesClustersPage = readFileSync(resolve(root, 'src/pages/KubernetesClustersPage.tsx'), 'utf8');
const pendingAgentSetup = readFileSync(resolve(root, 'src/components/common/PendingAgentSetup.tsx'), 'utf8');
const pendingClusterSetup = readFileSync(resolve(root, 'src/components/dashboard/PendingClusterSetup.tsx'), 'utf8');
const styles = readFileSync(resolve(root, 'src/styles.css'), 'utf8');

describe('cluster catalog and inspector layout', () => {
  it('uses a restrained inventory summary modeled after target inventory surfaces', () => {
    expect(dashboard).toContain('data-cluster-inventory-summary="true"');
    expect(dashboard).toContain("md:grid-cols-[minmax(15rem,1.35fr)_repeat(4,minmax(7rem,1fr))]");
    expect(dashboard).toContain("t('dashboard.clusterInventoryTitle')");
    expect(dashboard).toContain("t(hasUnloadedClusters ? 'dashboard.loadedClusterInventoryBody' : 'dashboard.clusterInventoryBody')");
    expect(dashboard).toContain("t('dashboard.clusters')");
    expect(dashboard).toContain("t('dashboard.attention')");
    expect(dashboard).toContain("t('dashboard.setupRequired')");
    expect(dashboard).toContain("t('dashboard.active')");
    expect(dashboard).not.toContain('getPostureClass');
    expect(dashboard).not.toContain('Global Status:');
  });

  it('uses workflow-style catalog cards instead of a column-heavy table', () => {
    expect(dashboard).toContain("import { ClusterCatalog } from '@/components/dashboard/ClusterCatalog'");
    expect(kubernetesClustersPage).toContain('flex min-h-0 flex-1 flex-col overflow-y-auto custom-scrollbar xl:overflow-hidden');
    expect(kubernetesClustersPage).toContain('catalogFooter={workspaceId ? (');
    expect(dashboard).toContain('xl:h-full xl:overflow-hidden');
    expect(dashboard).toContain('footer={catalogFooter}');
    expect(clusterCatalog).toContain('data-cluster-catalog-cards="true"');
    expect(clusterCatalog).toContain('data-cluster-card-scroll-region="true"');
    expect(clusterCatalog).toContain('const ClusterCatalogCard: React.FC');
    expect(clusterCatalog).toContain('grid min-w-0 shrink-0 gap-2">');
    expect(clusterCatalog).toContain('flex min-h-0 flex-col gap-2.5 overflow-y-auto pb-1 pr-2 custom-scrollbar stable-scrollbar-gutter xl:flex-1');
    expect(clusterCatalog).toContain('cluster-catalog-scrollbar');
    expect(styles).toContain('.cluster-catalog-scrollbar::-webkit-scrollbar');
    expect(styles).toContain('width: 1px;');
    expect(styles).toContain('.cluster-catalog-scrollbar::-webkit-scrollbar-thumb');
    expect(styles).toContain('rgb(var(--text-muted-rgb) / 22%)');
    expect(clusterCatalog).toContain('xl:items-stretch xl:overflow-hidden');
    expect(clusterCatalog).toContain('xl:h-full xl:min-h-0 xl:overflow-hidden');
    expect(clusterCatalog).not.toContain('xl:h-full xl:flex-1 xl:overflow-y-auto');
    expect(clusterCatalog).toContain('xl:items-stretch');
    expect(clusterCatalog).toContain('controls?: React.ReactNode;');
    expect(clusterCatalog).toContain('controls && (');
    expect(dashboard).toContain('controls={controls}');
    expect(clusterCatalog).toContain('data-cluster-card-select="true"');
    expect(clusterCatalog).toContain('pointer-events-none relative z-10');
    expect(clusterCatalog).toContain('gap-2.5 px-3.5 py-3');
    expect(clusterCatalog).toContain('const [now, setNow] = useState(() => Date.now());');
    expect(clusterCatalog).toContain('window.setInterval(() => setNow(Date.now()), 1000)');
    expect(clusterCatalog).toContain('aria-current={selected ? \'true\' : undefined}');
    expect(clusterCatalog).toContain('aria-pressed={selected}');
    expect(clusterCatalog).toContain('onSelectedClusterIdChange(cluster.id)');
    expect(clusterCatalog).toContain('aria-label={`Select cluster ${cluster.name}${selected ? \', selected\' : \'\'}`}');
    expect(clusterCatalog).toContain("data-cluster-row-action={requiresAgentInstall ? 'install-agent' : 'view'}");
    expect(clusterCatalog).toContain("import { Tooltip } from '@/components/common/Tooltip'");
    expect(clusterCatalog).toContain("requiresAgentInstall ? t('dashboard.installAgent') : t('dashboard.viewCluster')");
    expect(clusterCatalog).toContain("requiresAgentInstall ? t('dashboard.installAgentNamed', { name: cluster.name }) : t('dashboard.viewClusterNamed', { name: cluster.name })");
    expect(clusterCatalog).not.toContain("title={t('dashboard.viewClusterNamed', { name: cluster.name })}");
    expect(clusterCatalog).toContain('type-row-title block min-w-0 break-words text-ui-text');
    expect(clusterCatalog).toContain('flex min-w-0 items-center gap-2.5');
    expect(clusterCatalog).toContain('items-center gap-1.5 sm:justify-end');
    expect(clusterCatalog).toContain('inline-flex h-8 w-8 items-center justify-center rounded-md border border-ui-border bg-ui-surface');
    expect(clusterCatalog).not.toContain('data-cluster-title-action="view"');
    expect(clusterCatalog).not.toContain('underline decoration-ui-text-muted/70 decoration-1 underline-offset-4');
    expect(clusterCatalog).not.toContain('data-cluster-card-action="open"');
    expect(clusterCatalog).not.toContain("t('dashboard.openCluster')");
    expect(clusterCatalog).toContain('formatLastUpdated(cluster.lastUpdate, now)');
    expect(clusterCatalog).toContain('const ClusterCardFact: React.FC');
    expect(clusterCatalog).toContain('grid min-w-0 grid-cols-2 gap-1.5 lg:grid-cols-4');
    expect(clusterCatalog).toContain('grid min-h-[3.75rem] min-w-0 content-start gap-0.5');
    expect(clusterCatalog).toContain('type-micro-label flex min-w-0 items-center gap-1.5');
    expect(clusterCatalog).toContain('type-caption min-w-0 break-words text-ui-text-muted');
    expect(clusterCatalog).toContain('icon={ICONS.Cpu}');
    expect(clusterCatalog).toContain('icon={ICONS.HardDrive}');
    expect(clusterCatalog).toContain('icon={ICONS.Shield}');
    expect(clusterCatalog).toContain('icon={ICONS.Activity}');
    expect(clusterCatalog).toContain("label={t('dashboard.issues')}");
    expect(clusterCatalog).toContain("selected ? 'border-accent/45 bg-ui-surface outline outline-1 -outline-offset-1 outline-accent/35 ring-2 ring-accent/10 shadow-sm'");
    expect(clusterCatalog).not.toContain("t('dashboard.clusterCatalogDescription')");
    expect(clusterCatalog).not.toContain('border-t border-ui-border/70');
    expect(clusterCatalog).not.toContain('data-cluster-catalog-list="true"');
    expect(clusterCatalog).not.toContain('const clusterCatalogGridClass');
    expect(clusterCatalog).not.toContain('const CatalogCell: React.FC<CatalogCellProps>');
    expect(clusterCatalog).not.toContain("['Cluster', 'State', 'Inventory', 'Telemetry', '']");
    expect(clusterCatalog).not.toContain('actionCardButtonClassName');
    expect(clusterCatalog).not.toContain('className="type-caption min-w-0 rounded-md text-left leading-5');
    expect(clusterCatalog).not.toContain('bg-accent-soft/35');
  });

  it('keeps status text-led and reserves semantic color for exception states', () => {
    expect(clusterCatalog).toContain('function getClusterStatusClass');
    expect(clusterCatalog).toContain("requiresAgentInstall || status === HealthStatus.GREEN");
    expect(clusterCatalog).toContain("'border-ui-border bg-ui-bg text-ui-text-muted'");
    expect(clusterCatalog).toContain("'border-status-warning/25 bg-status-warning-soft text-status-warning-text'");
    expect(clusterCatalog).toContain("'border-status-danger/25 bg-status-danger-soft text-status-danger-text'");
    expect(clusterCatalog).toContain('function getClusterStateReason');
    expect(clusterCatalog).toContain('issueSummary: ControlPlaneTargetIssueSummary | undefined');
    expect(clusterCatalog).toContain("t('dashboard.clusterStateCheckingIssues')");
    expect(clusterCatalog).toContain("t('dashboard.clusterStateCriticalIssues', { count: issueSummary.critical })");
    expect(clusterCatalog).toContain("t('dashboard.clusterStateIssues', { count: issueSummary.total })");
    expect(clusterCatalog).toContain("t('dashboard.clusterStateCritical')");
    expect(clusterCatalog).toContain("t('dashboard.clusterStateReady')");
    expect(clusterCatalog).not.toContain("t('dashboard.clusterStateCriticalFindings'");
    expect(clusterCatalog).not.toContain("t('dashboard.clusterStateFindings'");
    expect(clusterCatalog).not.toContain('bg-status-success-soft text-status-success-text');
  });

  it('adds a selected-cluster display panel with operationally useful sections', () => {
    expect(dashboard).toContain('useState<string | undefined>()');
    expect(dashboard).toContain('const selectedCluster = kubernetesClusters.find((cluster) => cluster.id === selectedClusterId);');
    expect(dashboard).toContain('if (selectedClusterId && !kubernetesClusters.some((cluster) => cluster.id === selectedClusterId))');
    expect(dashboard).not.toContain('kubernetesClusters[0]?.id');
    expect(dashboard).not.toContain('|| kubernetesClusters[0]');
    expect(clusterCatalog).toContain("import { AnimatePresence, motion, useReducedMotion } from 'framer-motion'");
    expect(clusterCatalog).toContain("import { Button } from '@/components/common/Button'");
    expect(clusterCatalog).toContain('const shouldReduceMotion = useReducedMotion();');
    expect(clusterCatalog).toContain('<AnimatePresence mode="wait" initial={false}>');
    expect(clusterCatalog).toContain("key={selectedCluster?.id ?? 'cluster-selection-guide'}");
    expect(clusterCatalog).toContain("transition={shouldReduceMotion ? { duration: 0.01 } : { duration: 0.16, ease: [0.22, 1, 0.36, 1] }}");
    expect(clusterCatalog).toContain('const ClusterSelectionGuide: React.FC');
    expect(clusterCatalog).toContain('data-cluster-display-panel-empty="true"');
    expect(clusterCatalog).toContain("t('dashboard.selectClusterTitle')");
    expect(clusterCatalog).toContain("t('dashboard.selectClusterScope')");
    expect(clusterCatalog).toContain('Icon: ICONS.Shield');
    expect(clusterCatalog).toContain('Icon: ICONS.Activity');
    expect(clusterCatalog).toContain('Icon: ICONS.LayoutGrid');
    expect(clusterCatalog).toContain("selectedCluster ? (");
    expect(clusterCatalog).toContain('data-cluster-display-panel="true"');
    expect(clusterCatalog).toContain('const ClusterInspector: React.FC');
    expect(clusterCatalog).toContain('xl:flex xl:h-full xl:min-h-0 xl:flex-col');
    expect(clusterCatalog).toContain('xl:flex-1 xl:overflow-hidden');
    expect(clusterCatalog).toContain("import { getClusterTelemetrySnapshot } from '@/components/dashboard/clusterTelemetryModel'");
    expect(clusterCatalog).toContain("import { ClusterTelemetryPanel } from '@/components/dashboard/ClusterTelemetryPanel'");
    expect(clusterCatalog).toContain('<ClusterTelemetryPanel cluster={cluster} now={now} />');
    expect(clusterTelemetryPanel).toContain('export const ClusterTelemetryPanel: React.FC');
    expect(clusterTelemetryPanel).toContain('data-cluster-telemetry-panel="true"');
    expect(clusterTelemetryPanel).toContain('const hasCpuTrend = cpuPoints.length >= 2;');
    expect(clusterTelemetryPanel).toContain('const hasMemoryTrend = memoryPoints.length >= 2;');
    expect(clusterTelemetryPanel).not.toContain('formatRelativeTime');
    expect(clusterTelemetryPanel).toContain('formatCompactRelativeTime');
    expect(clusterTelemetryPanel).toContain('formatCompactRelativeTime(timeline[0].timestamp, { now })');
    expect(clusterTelemetryPanel).toContain('formatCompactRelativeTime(timeline[timeline.length - 1].timestamp, { now })');
    expect(clusterTelemetryPanel).toContain("t('dashboard.telemetryAxisEarlier')");
    expect(clusterTelemetryPanel).toContain("t('dashboard.telemetryAxisLabel')");
    expect(clusterTelemetryPanel).toContain("t('dashboard.telemetryAxisNow')");
    expect(clusterTelemetryPanel).toContain('viewBox="0 0 180 108"');
    expect(clusterTelemetryPanel).toContain('role="img"');
    expect(clusterTelemetryPanel).toContain('type SparklinePoint = { timestamp: number; value: number };');
    expect(clusterTelemetryPanel).toContain('function buildSparklinePath(points: SparklinePoint[], startTimestamp: number, endTimestamp: number');
    expect(clusterTelemetryPanel).toContain('const x = timeRange <= 0 ? width / 2 : ((point.timestamp - startTimestamp) / timeRange) * width;');
    expect(clusterTelemetryPanel).not.toContain('const TelemetryLane: React.FC');
    expect(clusterTelemetryPanel).not.toContain('function getMetricRange');
    expect(clusterTelemetryPanel).not.toContain('formatCpuAxisValue');
    expect(clusterTelemetryPanel).not.toContain('formatMemoryAxisValue');
    expect(clusterTelemetryPanel).not.toContain("t('dashboard.telemetryAxisHigh')");
    expect(clusterTelemetryPanel).not.toContain("t('dashboard.telemetryAxisLow')");
    expect(clusterTelemetryPanel).not.toContain("t('dashboard.telemetryAxisStart')");
    expect(clusterTelemetryPanel).not.toContain("t('dashboard.telemetryAxisEnd')");
    expect(clusterTelemetryModel).toContain('export function getMetricTimeline');
    expect(clusterTelemetryModel).toContain('export function getClusterTelemetrySnapshot');
    expect(clusterTelemetryModel).toContain('cpuPoints: Array<{ timestamp: number; value: number }>;');
    expect(clusterTelemetryModel).toContain('memoryPoints: Array<{ timestamp: number; value: number }>;');
    expect(clusterTelemetryModel).toContain('const cpuPoints = timeline');
    expect(clusterTelemetryModel).toContain('map((point) => ({ timestamp: point.timestamp, value: point.cpu }))');
    expect(clusterTelemetryModel).toContain('cpuDisplay: isUnavailableMetric(cluster.metrics.cpu)');
    expect(clusterTelemetryModel).toContain('cluster.metricHistory');
    expect(clusterTelemetryPanel).toContain('className="stroke-accent-strong"');
    expect(clusterTelemetryPanel).toContain('className="stroke-metric-blue"');
    expect(clusterTelemetryPanel).toContain('{hasCpuTrend && cpuPath &&');
    expect(clusterTelemetryPanel).toContain('{hasMemoryTrend && memoryPath &&');
    expect(clusterCatalog).toContain("t('dashboard.scopeAndSafeguards')");
    expect(clusterCatalog).toContain("t('app.inventory')");
    expect(clusterCatalog).toContain('function interactiveAttentionClass');
    expect(clusterCatalog).toContain('hover:border-status-danger/40 hover:bg-status-danger-soft hover:text-status-danger-text');
    expect(clusterCatalog).not.toContain('hover:border-accent/35 hover:bg-accent-soft/45');
    expect(clusterCatalog).toContain('buildScopePolicyItems(cluster, t)');
    expect(clusterCatalog).not.toContain("t('dashboard.agentConnection')");
    expect(clusterCatalog).not.toContain("t('dashboard.telemetryStream')");
    expect(clusterCatalog).toContain("t('dashboard.namespaceScope')");
    expect(clusterCatalog).toContain("t('dashboard.writeConfirmation')");
    expect(clusterCatalog).not.toContain("t('dashboard.mcpTools')");
    expect(clusterCatalog).toContain('type ResourceFamilyKey = \'workloads\' | \'network\' | \'storage\' | \'cluster\';');
    expect(clusterCatalog).toContain('function getResourceFamilyCount');
    expect(clusterCatalog).toContain('cluster.resourceSummary?.resourceFamilyCounts?.[family]');
    expect(clusterCatalog).toContain('const resourceFamilyItems = buildResourceFamilyItems(cluster, t);');
    expect(clusterCatalog).toContain("data-cluster-display-action={requiresAgentInstall ? 'install-agent' : 'view'}");
    expect(clusterCatalog).toContain('variant="accent"');
    expect(clusterCatalog).toContain('data-cluster-issue-banner-action="view-overview"');
    expect(clusterCatalog).toContain('data-cluster-setup-banner-action="install-agent"');
    expect(clusterCatalog).toContain("aria-label={t('dashboard.viewClusterIssuesNamed', { name: cluster.name })}");
    expect(clusterCatalog).not.toContain('<span className="type-micro-label shrink-0 text-ui-text-muted">{t(\'dashboard.viewCluster\')}</span>');
    expect(clusterCatalog).toContain('ml-[3.125rem] min-w-0');
    expect(clusterCatalog).toContain("t('resources.families.label')");
    expect(clusterCatalog).toContain("t('resources.families.workloads')");
    expect(clusterCatalog).toContain("t('resources.families.network')");
    expect(clusterCatalog).toContain("t('resources.families.storage')");
    expect(clusterCatalog).toContain("t('resources.families.cluster')");
    expect(clusterCatalog).not.toContain("t('dashboard.details')");
    expect(clusterCatalog).not.toContain('getWriteToolCount(cluster)');
    expect(clusterCatalog).not.toContain('formatUserDateTime(cluster.lastUpdate');
    expect(clusterCatalog).not.toContain('ClusterResourceChart');
    expect(clusterCatalog).not.toContain("t('dashboard.recentActivity')");
    expect(clusterCatalog).not.toContain('formatRelativeTime');
  });

  it('keeps diagnostics, setup, settings, and destructive actions deliberate', () => {
    expect(pendingClusterSetup).toContain('actionDataAttribute="data-cluster-setup-action"');
    expect(clusterCatalog).toContain('<PendingClusterSetup clusterId={cluster.id} onInstallAgent={onInstallAgent} />');
    expect(pendingClusterSetup).toContain('<PendingAgentSetup');
    expect(pendingAgentSetup).toContain('className="pointer-events-auto min-h-[4.25rem] border-t border-ui-border py-5"');
    expect(clusterCatalog).toContain("t('dashboard.viewCluster')");
    expect(clusterCatalog).toContain("data-cluster-row-action={requiresAgentInstall ? 'install-agent' : 'view'}");
    expect(clusterCatalog).toContain('<ICONS.Eye className="h-4 w-4" aria-hidden="true" />');
    expect(clusterCatalog).toContain('<ICONS.Wrench className="h-4 w-4" aria-hidden="true" />');
    expect(clusterCatalog).toContain("data-cluster-display-action={requiresAgentInstall ? 'install-agent' : 'view'}");
    expect(clusterCatalog).toContain("onInstallAgent?.(cluster.id)");
    expect(pendingClusterSetup).toContain('showAction={false}');
    expect(pendingClusterSetup).toContain('showFooter={false}');
    expect(pendingAgentSetup).toContain('h-[238px] min-w-0 shrink-0 overflow-hidden rounded-md border border-ui-border bg-ui-bg/35');
    expect(clusterCatalog).not.toContain('data-cluster-overflow-action="view"');
    expect(clusterCatalog).toContain('onSelectKubernetesCluster(cluster);');
    expect(pendingClusterSetup).toContain("t('dashboard.installAgent')");
    expect(clusterCatalog).toContain('data-cluster-overflow-action="toggle"');
    expect(clusterCatalog).toContain('data-cluster-overflow-action="settings"');
    expect(clusterCatalog).toContain('onOpenSettings={requiresAgentInstall ? undefined : onOpenSettings}');
    expect(clusterCatalog).toContain('data-cluster-overflow-action="delete"');
    expect(clusterCatalog).toContain('onClose={() =>');
    expect(clusterCatalog).toContain('aria-haspopup="menu"');
    expect(clusterCatalog).toContain("aria-label={t('dashboard.clusterActionsFor', { name: cluster.name })}");
    expect(dashboard).toContain("window.addEventListener('click', closeMenu);");
    expect(dashboard).toContain("event.key === 'Escape'");
    expect(clusterCatalog).not.toContain('data-cluster-row-action="delete"');
  });

  it('removes chart-card telemetry loading from the catalog page', () => {
    expect(dashboard).toContain("import { cardClassName } from '@/components/common/Card'");
    expect(clusterCatalog).toContain('formatLastUpdated,');
    expect(clusterTelemetryPanel).toContain("markerClassName: 'bg-accent-strong'");
    expect(clusterTelemetryPanel).toContain("markerClassName: 'bg-metric-blue'");
    expect(clusterCatalog).toContain('const telemetryFreshness = getTelemetryFreshness(cluster);');
    expect(dashboard).not.toContain("import { controlPlaneApi } from '@/services/controlPlaneApi'");
    expect(kubernetesClustersPage).toContain('function clusterMatchesCatalogState');
    expect(kubernetesClustersPage).toContain('function mergeClustersById');
    expect(kubernetesClustersPage).toContain('for (const cluster of secondary) byId.set(cluster.id, cluster);');
    expect(kubernetesClustersPage).toContain('loadedClusterPageItems');
    expect(kubernetesClustersPage).toContain('const hasActiveFilter = Boolean(query.trim()) || status !== \'all\';');
    expect(kubernetesClustersPage).not.toContain("status === 'connected' ? 'online'");
    expect(kubernetesClustersPage).toContain('setLoadedClusterPageItems((current) =>');
    expect(kubernetesClustersPage).toContain('onAppendWorkspaceKubernetesClusters?.(workspaceId, page.items);');
    expect(kubernetesClustersPage).toContain('hasActiveClusterFilter={hasActiveFilter}');
    expect(kubernetesClustersPage).not.toContain('onReplaceWorkspaceKubernetesClusters');
    expect(dashboard).toContain('hasActiveClusterFilter?: boolean;');
    expect(dashboard).toContain('kubernetesClusters.length > 0 || hasActiveClusterFilter');
    expect(clusterCatalog).toContain('const ClusterCatalogEmptyState');
    expect(clusterCatalog).toContain('hasActiveFilter?: boolean;');
    expect(clusterCatalog).toContain("t('dashboard.noMatchingClusters')");
    expect(kubernetesClustersPage).toContain("controlPlaneApi.getWorkspaceClusterMetricsHistory(targetWorkspaceId, clusterIds, { window: '6h', limit: 48 })");
    expect(kubernetesClustersPage).toContain('metricHistoryByClusterId');
    expect(kubernetesClustersPage).toContain('setMetricHistoryByClusterId({});');
    expect(kubernetesClustersPage).toContain('const activeConnectedClusterIds = new Set(connectedClusters.map((cluster) => cluster.id));');
    expect(kubernetesClustersPage).toContain('}, [metricHistoryFetchKey]);');
    expect(kubernetesClustersPage).not.toContain('}, [kubernetesClusters, metricHistoryFetchKey]);');
    expect(kubernetesClustersPage).toContain("getAgentConnectionState(cluster) === 'connected' && Object.prototype.hasOwnProperty.call(metricHistoryByClusterId, cluster.id)");
    expect(kubernetesClustersPage).toContain('controlPlaneApi.getTargetIssueSummary(cluster.workspaceId, cluster.id)');
    expect(kubernetesClustersPage).toContain('issueSummaryByClusterId');
    expect(kubernetesClustersPage).toContain('CLUSTER_ISSUE_SUMMARY_REFRESH_MS = 30000');
    expect(dashboard).toContain('issueSummaryByClusterId?: Record<string, ControlPlaneTargetIssueSummary | undefined>');
    expect(dashboard).toContain('issueSummaryByClusterId={issueSummaryByClusterId}');
    expect(clusterCatalog).toContain('issueSummaryByClusterId?: Record<string, ControlPlaneTargetIssueSummary | undefined>');
    expect(clusterCatalog).not.toContain("import { ClusterResourceChart");
    expect(clusterCatalog).not.toContain('getWorkspaceClusterMetricsHistory');
    expect(clusterCatalog).not.toContain('metricHistoryByClusterId');
    expect(clusterCatalog).not.toContain('<ClusterResourceChart cluster={cluster}');
    expect(clusterTelemetryPanel).not.toContain('controlPlaneApi');
  });

  it('uses the shared dialog shell for delete-cluster confirmation', () => {
    expect(dashboard).toContain("import { Dialog } from '@/components/common/Dialog'");
    expect(dashboard).toContain("import { Trans, useTranslation } from 'react-i18next'");
    expect(dashboard).toContain('titleId="delete-cluster-title"');
    expect(dashboard).toContain('closeDisabled={isDeletingCluster}');
    expect(dashboard).toContain('i18nKey="dashboard.deleteClusterConfirmationLabel"');
    expect(dashboard).toContain('font-extrabold text-status-danger-text');
  });

  it('keeps long cluster names readable with exact-name title access', () => {
    expect(clusterCatalog).toContain('title={cluster.name}>{cluster.name}</span>');
    expect(clusterCatalog).toContain("data-cluster-row-action={requiresAgentInstall ? 'install-agent' : 'view'}");
    expect(clusterCatalog).not.toContain('data-cluster-title-action="view"');
    expect(clusterCatalog).not.toContain('cursor-pointer rounded-sm');
    expect(clusterCatalog).toContain('<span className="type-row-title block min-w-0 break-words text-ui-text [overflow-wrap:anywhere]" title={cluster.name}>{cluster.name}</span>');
    expect(clusterCatalog).toContain('<ClusterMetadataLine cluster={cluster} t={t} />');
    expect(clusterCatalog).not.toContain('type-panel-title line-clamp-2 break-words');
  });
});
