import { describe, expect, it } from 'vitest';
import { buttonComponent, chatView, conversationHistory, enLocale, zhLocale } from '@/stylesTestSupport';

describe('target chat history rail contracts', () => {
  it('uses a compact assistant rail for search and chats across responsive layouts', () => {
    expect(chatView).toContain("import { MessagesSquare, Plus, Search, Upload } from 'lucide-react';");
    expect(chatView).toContain("aria-label={t('chat.assistantNavigation')}");
    expect(chatView).toContain('className="relative z-20 flex h-full w-12 shrink-0 flex-col items-center gap-1 border-r border-ui-border bg-ui-surface py-2"');
    expect(chatView).toContain('const [isHistorySearchPageOpen, setIsHistorySearchPageOpen] = React.useState(false);');
    expect(chatView).toContain('const openHistorySearch = () => {');
    expect(chatView).toContain('const toggleHistoryChats = (event: React.MouseEvent<HTMLButtonElement>) => {');
    expect(chatView).toMatch(/const openHistorySearch = \(\) => \{\s+setIsHistoryOpen\(false\);\s+setIsHistorySearchPageOpen\(true\);/);
    expect(chatView).toMatch(/const selectSessionFromSearch = \(sessionId: string\) => \{\s+setIsHistorySearchPageOpen\(false\);\s+selectSession\(sessionId\);/);
    expect(chatView).toMatch(/const createSessionFromSearch = \(\) => \{\s+setIsHistorySearchPageOpen\(false\);\s+handleCreateSessionClick\(\);/);
    expect(chatView).toContain('data-chat-history-trigger="search"');
    expect(chatView).toContain('data-chat-history-trigger="chats"');
    expect(chatView).toContain('if (isHistorySearchPageOpen) focusHistorySearch();');
    expect(conversationHistory).toContain('data-chat-history-search="true"');
    expect(chatView).toContain('<Search className="h-4 w-4" aria-hidden="true" />');
    expect(chatView).toContain('<MessagesSquare className="h-4 w-4" aria-hidden="true" />');
    expect(chatView).toContain('relative hidden h-full shrink-0 overflow-hidden border-r border-ui-border bg-ui-surface shadow-sm lg:flex');
    expect(chatView).toContain('style={{ width: historyPanelWidth }}');
    expect(chatView).toContain('data-chat-history-resize-handle="true"');
    expect(chatView).toContain('onPointerDown={startHistoryResize}');
    expect(chatView).toContain('onKeyDown={handleHistoryResizeKeyDown}');
    expect(chatView).toContain('resolveDraggedChatHistoryWidth({');
    expect(chatView).toContain('if (nextWidth === null) {');
    expect(chatView).toContain('collapseHistoryPanel();');
    expect(chatView).not.toContain('resolveReleasedChatHistoryWidth');
    expect(chatView).toContain('absolute inset-0 z-[110] bg-ui-text/20 dark:bg-ui-bg/65 lg:hidden');
    expect(chatView).toContain('absolute left-12 top-0 flex h-full w-[min(21rem,calc(100vw-5rem))]');
    expect(chatView).toContain('document.getElementById(historySearchPageId)');
    expect(chatView).toContain("?.querySelector<HTMLInputElement>('[data-chat-history-search=\"true\"]')");
    expect(chatView).toContain('shouldDismissHistoryOnKeyDown(event.key, usesOverlayHistory)');
    expect(chatView).toContain('if (event.target === event.currentTarget) setIsHistoryOpen(false);');
    expect(chatView).toMatch(/window\.setTimeout\(\(\) => \{\s+if \(document\.contains\(restoreTarget\)\) \{\s+restoreTarget\.focus\(\{ preventScroll: true \}\);/);
    expect(chatView).not.toContain('aria-pressed={isHistoryOpen}');
    expect(chatView).not.toContain('absolute left-0 top-1/2 z-20');
    expect(chatView).toContain('variant="tertiary"');
    expect(chatView).toContain('aria-controls={`${desktopHistoryPanelId} ${mobileHistoryPanelId}`}');
    expect(chatView).toContain('aria-controls={historySearchPageId}');
    expect(chatView).not.toContain('aria-expanded={isSearchRailActive}');
    expect(chatView).toContain('aria-expanded={isChatsRailActive}');
    expect(buttonComponent).toContain("icon: 'h-11 w-11 p-0 sm:h-9 sm:w-9'");
    expect(chatView).toContain("className={isSearchRailActive ? 'bg-ui-bg text-ui-text shadow-inner' : ''}");
    expect(chatView).toContain("className={isChatsRailActive ? 'bg-ui-bg text-ui-text shadow-inner' : ''}");
    expect(chatView).toContain('className="w-full whitespace-nowrap lg:w-auto"');
    expect(chatView).not.toContain('[clip-path:polygon');
    expect(conversationHistory).toContain("t('chat.chats')");
    expect(conversationHistory).toContain("t('chat.searchChats')");
    expect(conversationHistory).toContain("mode?: 'page' | 'panel';");
    expect(conversationHistory).toContain("const isPage = mode === 'page';");
    expect(conversationHistory).toContain("variant=\"primary\"");
    expect(chatView).toContain('mode="page"');
    expect(chatView).toContain('onCreateSession={createSessionFromSearch}');
    expect(chatView).toContain('onSelectSession={selectSessionFromSearch}');
    expect(conversationHistory).toContain('const visibleSessions = normalizedSearchValue');
    expect(conversationHistory).toContain('onClose?: () => void;');
    expect(conversationHistory).toMatch(/onSelectSession\(session\.id\);\s+onClose\?\.\(\);/);
    expect(chatView).toContain('onClose={() => setIsHistoryOpen(false)}');
    expect(chatView).not.toContain('xl:w-80');
    expect(enLocale).toContain("assistantNavigation: 'Assistant navigation'");
    expect(enLocale).toContain("searchChats: 'Search chats'");
    expect(enLocale).toContain("resizeHistory: 'Resize conversation history'");
    expect(zhLocale).toContain("assistantNavigation: '助手导航'");
    expect(zhLocale).toContain("searchChats: '搜索聊天'");
    expect(zhLocale).toContain("resizeHistory: '调整会话历史宽度'");
  });
});
