import type React from 'react';
import type { TFunction } from 'i18next';
import type { Components } from 'react-markdown';
import type { AssistantNavStatus } from '@/app/assistantNavStatus';
import type { AiRuntimeReadiness } from '@/features/ai/aiRuntimeReadiness';
import type { LiveRunTrace } from '@/features/targets/chat/types';
import type { ComposerAttachment, ComposerModelOption } from '@/features/targets/chat/components/targetChatViewHelpers';
import type { ChatMessage, ChatSession, ReasoningEffort } from '@/types';
import type { ControlPlaneTargetAssistantCapabilitiesPreview } from '@/services/control-plane/types';
import type { TargetDescriptor } from '@/features/targets/targetDescriptor';

export interface TargetChatViewBodyProps {
  activeRunId: string | null;
  activeSession: ChatSession | null;
  activeSessionId: string | null;
  aiRuntimeReadiness: AiRuntimeReadiness;
  allowedReasoningOptions: Array<{ value: string; labelKey: string }>;
  assistantMarkdownComponents: Components;
  assistantCapabilitiesPreview: ControlPlaneTargetAssistantCapabilitiesPreview | null;
  assistantCapabilitiesPreviewError: string;
  canApproveWriteActions: boolean;
  canCancelActiveRun: boolean;
  canChat: boolean;
  canDeleteSessions: boolean;
  canManageAiSettings: boolean;
  canPost: boolean;
  target: TargetDescriptor;
  composerActionLabel: string;
  composerAttachmentNotice: string;
  composerAttachments: ComposerAttachment[];
  composerModelOptions: ComposerModelOption[];
  composerRootRef: React.RefObject<HTMLDivElement | null>;
  composerSubmitUnavailableReason: string;
  composerTextareaRef: React.RefObject<HTMLTextAreaElement | null>;
  conversationNotice: string | null;
  deleteSessionError: string | null;
  deleteTargetSession: ChatSession | null;
  deletingSessionId: string | null;
  desktopHistoryPanelId: string;
  fileInputRef: React.RefObject<HTMLInputElement | null>;
  hasComposerSubmitPayload: boolean;
  hasConversationLoadError: boolean;
  hasEarlierMessages: boolean;
  handleAttachmentInputChange: (event: React.ChangeEvent<HTMLInputElement>) => void | Promise<void>;
  handleChatWindowDragEnter: (event: React.DragEvent<HTMLDivElement>) => void;
  handleChatWindowDragLeave: (event: React.DragEvent<HTMLDivElement>) => void;
  handleChatWindowDragOver: (event: React.DragEvent<HTMLDivElement>) => void;
  handleChatWindowDrop: (event: React.DragEvent<HTMLDivElement>) => void | Promise<void>;
  handleComposerKeyDown: (event: React.KeyboardEvent<HTMLTextAreaElement>) => void;
  handleCreateSessionClick: () => void;
  handleModelAndEffortChange: (value: ReasoningEffort) => void;
  handleModelChange: (option: ComposerModelOption) => void;
  historyButtonRef: React.RefObject<HTMLButtonElement | null>;
  historyControlLabel: string;
  historyPanelRef: React.RefObject<HTMLElement | null>;
  inputValue: string;
  isAssistantCapabilitiesPreviewLoading: boolean;
  isCancellingRun: boolean;
  isComposerRuntimeUnavailable: boolean;
  isFileDragActive: boolean;
  isHistoryOpen: boolean;
  isLoadingEarlierMessages: boolean;
  isModelMenuOpen: boolean;
  isModelSubmenuOpen: boolean;
  isPanel: boolean;
  isRunActive: boolean;
  isSessionsLoading: boolean;
  isSubmittingEdit: boolean;
  isWorkspaceAiSettingsLoading: boolean;
  lastUserMessageIndex: number;
  mobileHistoryPanelId: string;
  modelMenuPanelId: string;
  modelMenuRef: React.RefObject<HTMLDivElement | null>;
  modelSelectorId: string;
  modelSubmenuButtonId: string;
  modelSubmenuPanelId: string;
  newChatUnavailableReason: string;
  onApprove: (approvalId: string) => void | Promise<void>;
  onCancelRun: () => Promise<void>;
  onChatScroll: () => void;
  onDismissRecentActivityWarning: (sessionId: string) => void;
  onInputChange: (value: string) => void;
  onLoadEarlierMessages: () => void | Promise<void>;
  onOpenAiSettings: () => void;
  onOpenRecentActivitySession: (sessionId: string) => void;
  onReject: (approvalId: string) => void | Promise<void>;
  onClose?: () => void;
  onMaximize?: () => void;
  recentActivityWarning: ChatSession['recentActivityWarning'] | null;
  removeComposerAttachment: (attachmentId: string) => void;
  requestedToolAccessMode: 'read_only' | 'read_write';
  resolvedDescriptionKey: string;
  resolvedFooterKey: string;
  resolvedFooterNoAccessKey: string;
  resolvedInputPlaceholderKey: string;
  resolvedNoChatAccessKey: string;
  resolvedPromptBodyKey: string;
  resolvedPromptTitleKey: string;
  resolvedSuggestionKeys: string[];
  runTracesByRunId: Record<string, LiveRunTrace>;
  selectSession: (sessionId: string) => void;
  selectedEffort: ReasoningEffort;
  selectedEffortLabel: string;
  selectedModel: string;
  selectedModelLabel: string;
  selectedProvider: string;
  sendText: (text: string) => void | Promise<void>;
  sessionAssistantStatuses: Record<string, AssistantNavStatus>;
  sessions: ChatSession[];
  setEditingMessageValue: React.Dispatch<React.SetStateAction<string>>;
  setIsHistoryOpen: React.Dispatch<React.SetStateAction<boolean>>;
  setIsModelMenuOpen: React.Dispatch<React.SetStateAction<boolean>>;
  setIsModelSubmenuOpen: React.Dispatch<React.SetStateAction<boolean>>;
  setTraceExpandedByRunId: React.Dispatch<React.SetStateAction<Record<string, boolean>>>;
  shouldShowTranscriptSkeleton: boolean;
  submitComposerMessage: () => void | Promise<void>;
  t: TFunction;
  title: string;
  traceExpandedByRunId: Record<string, boolean>;
  transcriptRef: (node: HTMLDivElement | null) => void;
  userMarkdownComponents: Components;
  userTurnRunIdsByIndex: Map<number, string | undefined>;
  visibleMessages: ChatMessage[];
  workspaceAiSettingsError: string;
  startEditingMessage: (messageId: string, content: string) => void;
  cancelEditingMessage: () => void;
  closeDeleteSessionModal: () => void;
  confirmDeleteSession: () => void | Promise<void>;
  editingMessageId: string | null;
  editingMessageValue: string;
  isInFlightAssistantPlaceholder: (message: ChatMessage) => boolean;
  openDeleteSessionModal: (sessionId: string) => void;
  submitEditedMessage: (messageId: string) => void | Promise<void>;
}
